//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.04 at 08:22:48 AM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.apixio.com/Event", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.apixio.model.event;
