package com.apixio.nassembly.problem

object ProblemMetadataKeys extends Enumeration {

  // RAPS
  val TRANSACTION_DATE = Value("TRANSACTION_DATE")
  val FILE_MODE = Value("FILE_MODE")
  val PLAN_NUMBER = Value("PLAN_NUMBER")
  val OVERPAYMENT_ID = Value("OVERPAYMENT_ID")
  val OVERPAYMENT_ID_ERROR_CODE = Value("OVERPAYMENT_ID_ERROR_CODE")
  val PAYMENT_YEAR = Value("PAYMENT_YEAR")
  val PAYMENT_YEAR_ERROR = Value("PAYMENT_YEAR_ERROR")
  val DETAIL_NUMBER_ERROR = Value("DETAIL_NUMBER_ERROR")
  val PATIENT_CONTROL_NUMBER = Value("PATIENT_CONTROL_NUMBER")
  val PATIENT_HIC_NUMBER_ERROR = Value("PATIENT_HIC_NUMBER_ERROR")
  val CORRECTED_HIC_NUMBER = Value("CORRECTED_HIC_NUMBER")
  val PATIENT_DATE_OF_BIRTH = Value("PATIENT_DATE_OF_BIRTH")
  val PATIENT_DATE_OF_BIRTH_ERROR = Value("PATIENT_DATE_OF_BIRTH_ERROR")
  val PROVIDER_TYPE = Value("PROVIDER_TYPE")
  val DIAGNOSIS_CLUSTER_ERROR1 = Value("DIAGNOSIS_CLUSTER_ERROR1")
  val DIAGNOSIS_CLUSTER_ERROR2 = Value("DIAGNOSIS_CLUSTER_ERROR2")
  val RISK_ASSESSMENT_CODE_CLUSTERS = Value("RISK_ASSESSMENT_CODE_CLUSTERS")

  // MAO 004
  val HICN = Value("HICN")
  val PLAN_SUBMISSION_DATE = Value("PLAN_SUBMISSION_DATE")
  val ENCOUNTER_CLAIM_TYPE = Value("ENCOUNTER_CLAIM_TYPE")
  val MA_CONTRACT_ID = Value("MA_CONTRACT_ID")
  val ORIGINAL_ENCOUNTER_ICN = Value("ORIGINAL_ENCOUNTER_ICN")
  val ENCOUNTER_TYPE_SWITCH = Value("ENCOUNTER_TYPE_SWITCH")
  val REPLACEMENT_ENCOUNTER_SWITCH = Value("REPLACEMENT_ENCOUNTER_SWITCH")
  val ENCOUNTER_ICN = Value("ENCOUNTER_ICN")
  val SUBMISSION_FILE_TYPE = Value("SUBMISSION_FILE_TYPE")
  val REPORT_DATE = Value("REPORT_DATE")
  val PROCESSING_DATE = Value("PROCESSING_DATE")
  val SUBMISSION_INTERCHANGE_NUMBER = Value("SUBMISSION_INTERCHANGE_NUMBER")

  // Generic
  val CLAIM_TYPE = Value("CLAIM_TYPE")
  val DELETE_INDICATOR = Value("DELETE_INDICATOR")
  val ADD_OR_DELETE_FLAG = Value("ADD_OR_DELETE_FLAG")



}
