package com.apixio.model.raps;

public interface RapsConstants {
    int DIAGNOSIS_CLUSTER_LENGTH = 32;
    int MAX_DIAGNOSIS_CLUSTERS = 10;
    int RISK_ASSESSMENT_CODE_CLUSTER_LENGTH = 4;
    int MAX_RISK_ASSESSMENT_CODE_CLUSTERS = 10;
    int RECORD_LENGTH = 512;
    String DATE_FORMAT = "yyyyMMdd";

    // RAPS known metadata
    String META_KEY_TRANSACTION_DATE = "TRANSACTION_DATE";
    String META_KEY_FILE_MODE = "FILE_MODE";
    String META_KEY_PLAN_NUMBER = "PLAN_NUMBER";
    String META_KEY_OVERPAYMENT_ID = "OVERPAYMENT_ID";
    String META_KEY_OVERPAYMENT_ID_ERROR = "OVERPAYMENT_ID_ERROR_CODE";
    String META_KEY_PAYMENT_YEAR = "PAYMENT_YEAR";
    String META_KEY_PAYMENT_YEAR_ERROR = "PAYMENT_YEAR_ERROR";
    String META_KEY_DETAIL_NUMBER_ERROR = "DETAIL_NUMBER_ERROR";
    String META_KEY_PATIENT_CONTROL_NUMBER = "PATIENT_CONTROL_NUMBER";
    String META_KEY_PATIENT_HIC_NUMBER_ERROR = "PATIENT_HIC_NUMBER_ERROR";
    String META_KEY_CORRECTED_HIC_NUMBER = "CORRECTED_HIC_NUMBER";
    String META_KEY_PATIENT_DOB = "PATIENT_DATE_OF_BIRTH";
    String META_KEY_PATIENT_DOB_ERROR = "PATIENT_DATE_OF_BIRTH_ERROR";
    String META_KEY_PROVIDER_TYPE = "PROVIDER_TYPE";
    String META_KEY_DELETE_INDICATOR = "DELETE_INDICATOR";
    String META_KEY_DIAGNOSIS_CLUSTER_ERROR1 = "DIAGNOSIS_CLUSTER_ERROR1";
    String META_KEY_DIAGNOSIS_CLUSTER_ERROR2 = "DIAGNOSIS_CLUSTER_ERROR2";
    String META_KEY_RISK_ASSESSMENT_CODE_CLUSTERS = "RISK_ASSESSMENT_CODE_CLUSTERS";

    // RAPS errors
    short CCC_SEQ_NUM_IS_OUT_OF_SEQUENCE = 309;
    short MISSING_OR_INVALID_HIC_NUMBER = 310;
    short AT_LEAST_ONE_DIAGNOSIS_CLUSTER_REQUIRED_ON_TRANSACTION_ERROR = 311;
    short SERVICE_FROM_DATE_NOT_WITHIN_MEDICARE_ENTITLEMENT_ERROR = 406;
    short SERVICE_FROM_DATE_NOT_WITHIN_MA_ORG_ENROLLMENT_ERROR = 408;
    short RISK_ASSESSMENT_CODE_IS_MISSING_ERROR = 419;
}
