apiVersion: v1
kind: Pod
metadata:
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
spec:
  nodeSelector:
    worker-type: jenkins-scaling
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  containers:
    - name: cloc
      image: 088921318242.dkr.ecr.us-west-2.amazonaws.com/apixio-devops/cloc:latest
      command: ["tail", "-f", "/dev/null"] #noop
      imagePullPolicy: Always
      workingDir: "/home/jenkins/agent"
      resources:
        requests:
          memory: "2Gi"
        limits:
          memory: "2Gi"
    - name: dind
      image: 088921318242.dkr.ecr.us-west-2.amazonaws.com/apixio-devops/dind:latest
      imagePullPolicy: Always
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        privileged: true
      resources:
        requests:
          memory: "10Gi"
        limits:
          memory: "10Gi"
      volumeMounts:
        - name: dockercerts
          mountPath: /certs
    - name: mvn
      image: 088921318242.dkr.ecr.us-west-2.amazonaws.com/apixio-devops/maven:latest-3-jdk-8-slim
      command: ["tail", "-f", "/dev/null"] #noop
      imagePullPolicy: Always
      workingDir: "/home/jenkins/agent"
      resources:
        requests:
          memory: "15Gi"
        limits:
          memory: "15Gi"
      env:
        - name: DOCKER_CERT_PATH
          value: "/certs/client"
        - name: DOCKER_HOST
          value: "tcp://localhost:2376"
        - name: DOCKER_TLS_VERIFY
          value: "true"
      volumeMounts:
        - name: pyirc
          mountPath: /home/jenkins/.pypirc
          subPath: .pypirc
        - name: ivy2
          mountPath: /home/jenkins/.ivy2/build.credentials
          subPath: build.credentials
        - name: ivy2
          mountPath: /home/jenkins/.ivy2/release.credentials
          subPath: release.credentials
        - name: m2
          mountPath: /home/jenkins/.m2/settings.xml
          subPath: settings.xml
        - name: dockercerts
          mountPath: /certs
  volumes:
    - name: ivy2
      configMap:
        name: jenkins-sbt-ivy2
    - name: m2
      configMap:
        name: jenkins-sbt-m2
    - name: pyirc
      configMap:
        name: jenkins-pyirc
    - name: dockercerts
      emptyDir: {}
