package com.apixio.model.cdi;

public enum BatchConfigType
{
    COVERAGE,
    DEMOGRAPHICS,
    DOCUMENTS,
    DOCMETADATA,
    FILTER,
    PROBLEMS,
    PROVIDERS,
    ENCOUNTERS,
    LAB_RESULTS,
    PRESCRIPTIONS,
    PROCEDURES,
    FFS_CLAIMS,
    FFS_CLAIMS_EXTENDED,
    RA_CLAIMS,
    RAPS,
    PAGES,
    MAO_004,
    XWALK,
    VENDOR_KNOWN_CODES,
    BIOMETRICS,
    SOCIAL_HISTORY;
}
