package com.apixio.model.owl.interfaces.donotimplement;

/**
 * AddressTypeValue
 * <p/>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: ${interfaceName} <br>
 *
 * @version generated on Thu Mar 31 14:23:07 PDT 2016 by jctoledo
 */


public enum AddressTypeValue {
    CURRENT,
    PERMANENT
}
