package com.apixio.model.owl.interfaces.donotimplement;

/**
 * OWL annotation driven imports
 **/

/**
 * AddressTypeValue
 * <p/>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: AddressType <br>
 *
 * @version generated on Thu Mar 31 14:23:07 PDT 2016 by jctoledo
 */

public interface AddressType extends SocialQuality {

    AddressTypeValue getAddressTypeValue();

    void setAddressTypeValue(AddressTypeValue en);


}