package com.apixio.model.owl.interfaces.donotimplement;

/**
 OWL annotation driven imports 
**/


/**
 * 
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: ApixioDate <br>
 * @version generated on Fri Mar 11 09:53:02 PST 2016 by jctoledo
 */

public interface ApixioDate  extends TimeMeasurment {


    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000303
     */

    /**
     * Gets all property values for the DateType property.<p>
     *
     *
     * @returns a collection of values for the DateType property.
     */
    DateType getDateType();


    /**
     * Adds a DateType property value.<p>
     *
     *
     * @param newDateType the DateType property value to be added
     */
    void setDateType(DateType newDateType);




}
