package com.apixio.model.owl.interfaces.donotimplement;

import java.util.Collection;

/**
 OWL annotation driven imports 
**/
import com.apixio.model.owl.interfaces.CareSite;
import com.apixio.model.owl.interfaces.Organization;
import org.joda.time.DateTime;
import java.net.URI;
import com.apixio.XUUID;


/**
 * 
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: CareSiteOrganization <br>
 * @version generated on Thu Mar 31 14:23:08 PDT 2016 by jctoledo
 */

public interface CareSiteOrganization  extends Organization, CareSite {





}
