package com.apixio.model.owl.interfaces.donotimplement;

/**
 * OWL annotation driven imports
 **/

import com.apixio.model.owl.interfaces.donotimplement.CareSiteTypeValue;
import com.apixio.model.owl.interfaces.donotimplement.SocialQuality;

/**
 * CareSiteTypeValue
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: CareSiteType <br>
 * @version generated on Fri Mar 11 09:53:00 PST 2016 by jctoledo
 */

public interface CareSiteType extends SocialQuality {

    CareSiteTypeValue getCareSiteTypeValue();

    void setCareSiteTypeValue(CareSiteTypeValue en);


}