package com.apixio.model.owl.interfaces.donotimplement;

/**
 * OWL annotation driven imports
 **/

import com.apixio.model.owl.interfaces.donotimplement.ClinicalRoleTypeValue;
import com.apixio.model.owl.interfaces.donotimplement.MedicalQuality;

/**
 * ClinicalRoleTypeValue
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: ClinicalRoleType <br>
 * @version generated on Fri Mar 11 09:53:00 PST 2016 by jctoledo
 */

public interface ClinicalRoleType extends MedicalQuality {

    ClinicalRoleTypeValue getClinicalRoleTypeValue();

    void setClinicalRoleTypeValue(ClinicalRoleTypeValue en);

}