package com.apixio.model.owl.interfaces.donotimplement;


/**
 * ClinicalRoleTypeValue
 * <p/>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: ${interfaceName} <br>
 *
 * @version generated on Fri Mar 11 09:53:00 PST 2016 by jctoledo
 */


public enum ClinicalRoleTypeValue {
    ADMINISTERING_PHYSICIAN,
    ATTENDING_PHYSICIAN,
    AUTHORING_PROVIDER,
    CONSULTING_PROVIDER,
    DIAGNOSING_PHYSICIAN,
    HOSPITAL_INPATIENT_OTHER_PROVIDER,
    HOSPITAL_INPATIENT_PRINCIPAL_PROVIDER,
    HOSPITAL_OUTPATIENT_PROVIDER,
    INTERPRETING_PHYSICIAN,
    MEDICAL_ASSISTANT,
    MEDICAL_HOME_PROVIDER,
    NURSE_PRACTITIONER,
    ORDERING_PHYSICIAN,
    PERFORMING_PHYSICIAN,
    PRESCRIBING_PHYSICIAN,
    PRIMARY_CARE_PROVIDER,
    REFERRING_PROVIDER,
    REVIEWING_PHYSICIAN,
    TECHNICAL_ASSISTANT,
    TREATING_PHYSICIAN
}
