package com.apixio.model.owl.interfaces.donotimplement;

import com.apixio.XUUID;
import com.apixio.model.owl.interfaces.ClinicalCode;

import java.util.Collection;

/**
 * OWL annotation driven imports
 **/


/**
 * <p/>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: CodedEntity <br>
 *
 * @version generated on Fri Mar 11 09:53:02 PST 2016 by jctoledo
 */

public interface CodedEntity extends MedicalCodeEntity {


/**
 * OWL annotation driven methods
 **/
    /**
     * source encounter
     */
    XUUID getSourceEncounterId();
    void setSourceEncounterId(XUUID anID);

    /**
     * primary medical professional
     */
    XUUID getPrimaryMedicalProfessional();
    void setMedicalProfessional(XUUID anId);

    /**
     * alternate medical professionals xuuids
     */
    Collection<XUUID> getAlternateMedicalProfessionalIds();
    void setAlternateMedicalProfessionalIds(Collection<XUUID> medicalPros);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000093
     */

    /**
     * Gets all property values for the CodedEntityClinicalCode property.<p>
     *
     *
     * @returns a collection of values for the CodedEntityClinicalCode property.
     */
    ClinicalCode getCodedEntityClinicalCode();


    /**
     * Adds a CodedEntityClinicalCode property value.<p>
     *
     *
     * @param newCodedEntityClinicalCode the CodedEntityClinicalCode property value to be added
     */
    void setCodedEntityClinicalCode(ClinicalCode newCodedEntityClinicalCode);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000206
     */

    /**
     * Gets all property values for the CodedEntityNames property.<p>
     *
     * @returns a collection of values for the CodedEntityNames property.
     * Collection<? extends String> getCodedEntityNames();
     *
     */
    Collection<String> getCodedEntityNames();

    /**
     * Add an element to the list
     *
     */
    Collection<String> addCodedEntityNames(String anItem);

    /**
     * get element from list by Id
     *
     */
    String getCodedEntityNamesById(XUUID anID);

    /**
     * Adds a CodedEntityNames property value.<p>
     *
     * @param newCodedEntityNames the CodedEntityNames property value to be added
     * void setCodedEntityNames(Collection<? extends String> newCodedEntityNames);
     *
     */
    void setCodedEntityNames(Collection<String> newCodedEntityNames);

}
