package com.apixio.model.owl.interfaces.donotimplement;

/**
 OWL annotation driven imports 
**/

import java.lang.Runnable;


/**
 * 
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: DataTransformation <br>
 * @version generated on Fri Mar 11 09:53:00 PST 2016 by jctoledo
 */

public interface DataTransformation  extends InformationProcessing, Runnable {


void run();



}
