package com.apixio.model.owl.interfaces.donotimplement;

/**
 * DateQualityValue
 * <p/>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: ${interfaceName} <br>
 *
 * @version generated on Thu Mar 31 15:40:44 PDT 2016 by jctoledo
 */


public enum DateQualityValue {
    ASSUMED,
    INFERRED,
    PROVIDED,
    UNKNOWN
}
