package com.apixio.model.owl.interfaces.donotimplement;

/**
 OWL annotation driven imports 
**/
import com.apixio.model.owl.interfaces.donotimplement.DateQualityValue;
import com.apixio.model.owl.interfaces.donotimplement.MeasurmentQuality;

/**
 * DateQualityValue
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: DateType <br>
 * @version generated on Fri Mar 11 09:53:00 PST 2016 by jctoledo
 */

public interface DateType extends MeasurmentQuality {

DateQualityValue getDateQualityValue();

void setDateQualityValue(DateQualityValue en);




}