package com.apixio.model.owl.interfaces.donotimplement;

/**
 * OWL annotation driven imports
 **/

import com.apixio.model.owl.interfaces.donotimplement.DocumentTypeValue;
import com.apixio.model.owl.interfaces.donotimplement.InformationContentQuality;

/**
 * DocumentTypeValue
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: DocumentType <br>
 * @version generated on Fri Mar 11 09:53:00 PST 2016 by jctoledo
 */

public interface DocumentType extends InformationContentQuality {

    DocumentTypeValue getDocumentTypeValue();

    void setDocumentTypeValue(DocumentTypeValue en);


}