package com.apixio.model.owl.interfaces.donotimplement;


/**
 * DocumentTypeValue
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: ${interfaceName} <br>
 * @version generated on Fri Mar 11 09:53:00 PST 2016 by jctoledo
 */


public enum DocumentTypeValue {
    ENCOUNTER_NOTE,
    IMAGE_OR_SCANNED,
    NARRATIVE,
    STRUCTURED_DOCUMENT
}
