package com.apixio.model.owl.interfaces.donotimplement;

import java.util.Collection;

/**
 * OWL annotation driven imports 
**/
import org.joda.time.DateTime;
import java.net.URI;
import com.apixio.XUUID;
import java.util.Collection;
import java.util.ArrayList;

/**
 * FeeForServiceInsuranceClaimTypeValue
 * 
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: FeeForServiceInsuranceClaimType <br>
 * @version generated on Thu Jan 05 15:29:11 PST 2017 by jctoledo
 */

public interface FeeForServiceInsuranceClaimType extends InformationContentQuality {

FeeForServiceInsuranceClaimTypeValue getFeeForServiceInsuranceClaimTypeValue();

void setFeeForServiceInsuranceClaimTypeValue(FeeForServiceInsuranceClaimTypeValue en);




}