package com.apixio.model.owl.interfaces.donotimplement;

import java.util.Collection;


/**
 * FeeForServiceInsuranceClaimTypeValue
 * ${dcdescription}
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: ${interfaceName} <br>
 * @version generated on Thu Jan 05 15:29:11 PST 2017 by jctoledo
 */


public enum FeeForServiceInsuranceClaimTypeValue {
  FFS
}
