package com.apixio.model.owl.interfaces.donotimplement;

/**
 * OWL annotation driven imports
 **/

/**
 * GenderValues
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: GenderType <br>
 * @version generated on Fri Mar 11 09:53:00 PST 2016 by jctoledo
 */

public interface GenderType extends BiologicalQuality {

    GenderValues getGenderValues();

    void setGenderValues(GenderValues en);


}