package com.apixio.model.owl.interfaces.donotimplement;

/**
 OWL annotation driven imports 
**/


/**
 * 
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: HealthMaintenanceOrganization <br>
 * @version generated on Fri Mar 11 09:53:03 PST 2016 by jctoledo
 */

public interface HealthMaintenanceOrganization  extends HealthCarePayor {





}
