package com.apixio.model.owl.interfaces.donotimplement;

import java.util.Collection;

/**
 OWL annotation driven imports 
**/
import com.apixio.XUUID;
import com.apixio.model.owl.interfaces.ContactDetails;
import com.apixio.model.owl.interfaces.Demographics;
import com.apixio.model.owl.interfaces.InsurancePolicy;


/**
 * 
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: Human <br>
 * @version generated on Fri Mar 11 09:53:02 PST 2016 by jctoledo
 */

public interface Human  extends Person {



    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000365
     */

    /**
     * Gets all property values for the Demographics property.<p>
     *
     * @returns a collection of values for the Demographics property.
     */
    Demographics getDemographics();


    /**
     * Adds a Demographics property value.<p>
     *
     * @param newDemographics the Demographics property value to be added
     */
    void setDemographics(Demographics newDemographics);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000424
     */

    /**
     * Gets all property values for the ContactDetails property.<p>
     *
     * @returns a collection of values for the ContactDetails property.
     */
    ContactDetails getContactDetails();


    /**
     * Adds a ContactDetails property value.<p>
     *
     * @param newContactDetails the ContactDetails property value to be added
     */
    void setContactDetails(ContactDetails newContactDetails);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000425
     */

    /**
     * Gets all property values for the AlternateContactDetailss property.<p>
     *
     * @returns a collection of values for the AlternateContactDetailss property.
     * Collection<? extends ContactDetails> getAlternateContactDetailss();
     */
    Collection<ContactDetails> getAlternateContactDetailss();

    /**
     * Add an element to the list
     */
    Collection<ContactDetails> addAlternateContactDetailss(ContactDetails anItem);

    /**
     * get element from list by Id
     */
    ContactDetails getAlternateContactDetailssById(XUUID anID);

    /**
     * Adds a AlternateContactDetailss property value.<p>
     *
     * @param newAlternateContactDetailss the AlternateContactDetailss property value to be added
     * void setAlternateContactDetailss(Collection<? extends ContactDetails> newAlternateContactDetailss);
     */
    void setAlternateContactDetailss(Collection<ContactDetails> newAlternateContactDetailss);


}
