package com.apixio.model.owl.interfaces.donotimplement;

/**
 OWL annotation driven imports 
**/


/**
 * 
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: InformationalEntityIdentifier <br>
 * @version generated on Fri Mar 11 09:53:01 PST 2016 by jctoledo
 */

public interface InformationalEntityIdentifier  extends Identifier, ProvenancedEntity {





}
