package com.apixio.model.owl.interfaces.donotimplement;

/**
 OWL annotation driven imports 
**/


import com.apixio.model.owl.interfaces.Procedure;

/**
 * 
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: InformationProcessing <br>
 * @version generated on Fri Mar 11 09:53:03 PST 2016 by jctoledo
 */

public interface InformationProcessing  extends Procedure {





}
