package com.apixio.model.owl.interfaces.donotimplement;

import java.util.Collection;

/**
 * OWL annotation driven imports 
**/
import org.joda.time.DateTime;
import java.net.URI;
import com.apixio.XUUID;

/**
 * InputDataTypeValue
 * 
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: InputDataType <br>
 * @version generated on Mon Jun 13 14:23:55 PDT 2016 by jctoledo
 */

public interface InputDataType extends InformationContentQuality {

InputDataTypeValue getInputDataTypeValue();

void setInputDataTypeValue(InputDataTypeValue en);




}