package com.apixio.model.owl.interfaces.donotimplement;

/**
 * InputDataTypeValue
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: ${interfaceName} <br>
 * @version generated on Thu Mar 31 15:40:44 PDT 2016 by jctoledo
 */


public enum InputDataTypeValue {
  STRUCTURED, UNSTRUCTURED, STRUCTURED_DOCUMENT, UNSTRUCTURED_DOCUMENT,

}
