package com.apixio.model.owl.interfaces.donotimplement;

/**
 * OWL annotation driven imports
 **/


/**
 * 
 * Any event that can be claimed to a health insurnace plan through a person's insurance policy
	*
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: InsuranceClaimableEvent <br>
 * @version generated on Fri Apr 15 09:08:45 PDT 2016 by jctoledo
 */

public interface InsuranceClaimableEvent  extends CodedEntity {





}
