package com.apixio.model.owl.interfaces.donotimplement;


/**
 * InsuranceClaimStatusValue
 * <p/>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: ${interfaceName} <br>
 *
 * @version generated on Fri Mar 11 09:53:00 PST 2016 by jctoledo
 */


public enum InsuranceClaimStatusValue {
    DELETED,
    PAID,
    REJECTED
}
