package com.apixio.model.owl.interfaces.donotimplement;

/**
 * OWL annotation driven imports
 **/

import com.apixio.model.owl.interfaces.donotimplement.InsuranceClaimStatusValue;
import com.apixio.model.owl.interfaces.donotimplement.SocialQuality;

/**
 * InsuranceClaimStatusValue
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: InsuranceClaimStatusType <br>
 * @version generated on Fri Mar 11 09:53:00 PST 2016 by jctoledo
 */

public interface InsuranceClaimStatusType extends SocialQuality {

    InsuranceClaimStatusValue getInsuranceClaimStatusValue();

    void setInsuranceClaimStatusValue(InsuranceClaimStatusValue en);


}