package com.apixio.model.owl.interfaces.donotimplement;

/**
 * OWL annotation driven imports
 **/

/**
 * LabFlagValue
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: LabFlagType <br>
 * @version generated on Fri Mar 11 09:53:00 PST 2016 by jctoledo
 */

public interface LabFlagType extends MeasurmentQuality {

    LabFlagValue getLabFlagValue();

    void setLabFlagValue(LabFlagValue en);


}
