package com.apixio.model.owl.interfaces.donotimplement;


/**
 * MaritalStatusValue
 * <p/>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: ${interfaceName} <br>
 *
 * @version generated on Fri Mar 11 09:53:00 PST 2016 by jctoledo
 */


public enum MaritalStatusValue {
    ANNULLED,
    DIVORCED,
    DOMESTIC_PARTNER,
    INTERLOCUTORY,
    LEGALLY_SEPARATED,
    MARRIED,
    NEVER_MARRIED,
    POLYGAMOUS,
    WIDOWED
}
