package com.apixio.model.owl.interfaces.donotimplement;

/**
 * OWL annotation driven imports
 **/

/**
 * MaritalStatusValue
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: MaritalStatusType <br>
 * @version generated on Fri Mar 11 09:53:00 PST 2016 by jctoledo
 */

public interface MaritalStatusType extends SocialQuality {

    MaritalStatusValue getMaritalStatusValue();

    void setMaritalStatusValue(MaritalStatusValue en);


}