package com.apixio.model.owl.interfaces.donotimplement;

/**
 OWL annotation driven imports 
**/
import com.apixio.model.owl.interfaces.donotimplement.ApixioObject;
import com.apixio.model.owl.interfaces.donotimplement.ProvenancedEntity;


/**
 * 
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: MaterialEntity <br>
 * @version generated on Fri Mar 11 09:53:03 PST 2016 by jctoledo
 */

public interface MaterialEntity  extends ApixioObject, ProvenancedEntity {





}
