package com.apixio.model.owl.interfaces.donotimplement;


/**
 * NameTypeValue
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: ${interfaceName} <br>
 * @version generated on Fri Mar 11 09:53:00 PST 2016 by jctoledo
 */


public enum NameTypeValue {
  BIRTH_NAME,
CURRENT_NAME,
MAIDEN_NAME,
NICK_NAME
}
