package com.apixio.model.owl.interfaces.donotimplement;

/**
 OWL annotation driven imports 
**/

import com.apixio.model.owl.interfaces.donotimplement.*;
import com.apixio.model.owl.interfaces.donotimplement.NameTypeValue;

/**
 * NameTypeValue
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: NameType <br>
 * @version generated on Fri Mar 11 09:53:00 PST 2016 by jctoledo
 */

public interface NameType extends SocialQuality {

NameTypeValue getNameTypeValue();

void setNameTypeValue(NameTypeValue en);




}