package com.apixio.model.owl.interfaces.donotimplement;

import com.apixio.model.owl.interfaces.donotimplement.ApixioProcess;

/**
 * OWL annotation driven imports
 **/


/**
 * <p/>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: Operation <br>
 *
 * @version generated on Thu Mar 31 16:06:26 PDT 2016 by jctoledo
 */

public interface Operation extends ApixioProcess {


}
