package com.apixio.model.owl.interfaces.donotimplement;

/**
 OWL annotation driven imports 
**/
import com.apixio.model.owl.interfaces.donotimplement.InformationContentQuality;
import com.apixio.model.owl.interfaces.donotimplement.OperationAnnotationValue;

/**
 * OperationAnnotationValue
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: OperationAnnotationType <br>
 * @version generated on Fri Mar 11 09:53:00 PST 2016 by jctoledo
 */

public interface OperationAnnotationType extends InformationContentQuality {

OperationAnnotationValue getOperationAnnotationValue();

void setOperationAnnotationValue(OperationAnnotationValue en);




}