package com.apixio.model.owl.interfaces.donotimplement;

/**
 OWL annotation driven imports 
**/

/**
 * ParserTypeValue
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: ParserType <br>
 * @version generated on Fri Mar 11 09:53:00 PST 2016 by jctoledo
 */

public interface ParserType extends InformationContentQuality {

ProcessorTypeValue getParserTypeValue();

void setParserTypeValue(ProcessorTypeValue en);




}