package com.apixio.model.owl.interfaces.donotimplement;

/**
 * Created by jctoledo on 9/13/16.
 */

/**
 * PatientEncounterSwitchTypeValue
 * ${dcdescription}
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: ${interfaceName} <br>
 * @version generated on Tue Sep 13 11:28:51 PDT 2016 by jctoledo
 */

public enum PatientEncounterSwitchTypeValue {
    LINKED_CHART_REVIEW,
    ORIGINAL_ENCOUNTER,
    REPLACEMENT_TO_AN_ORIGINAL_ENCOUNTER,
    REPLACEMENT_TO_AN_UNLINKED_CHART_REVIEW,
    REPLACEMENT_TO_A_LINKED_CHART_REVIEW,
    UNLINKED_CHART_REVIEW,
    VOID_TO_AN_UNLINKED_CHART_REVIEW,
    VOID_TO_A_LINKED_CHART_REVIEW,
    VOID_TO_ORIGINAL_ENCOUNTER
}
