package com.apixio.model.owl.interfaces.donotimplement;


/**
 * PatientEncounterTypeValue
 * <p/>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: ${interfaceName} <br>
 *
 * @version generated on Fri Mar 11 09:53:00 PST 2016 by jctoledo
 */


public enum PatientEncounterTypeValue {
    FACE_TO_FACE,
    HOSPITAL_INPATIENT,
    HOSPITAL_OUTPATIENT,
    NON_CLINICAL,
    PROFESSIONAL,
    REAL_TELEPHONY,
    VIRTUAL
}
