package com.apixio.model.owl.interfaces.donotimplement;

/**
 OWL annotation driven imports 
**/
import com.apixio.model.owl.interfaces.donotimplement.PatientEncounterTypeValue;

/**
 * PatientEncounterTypeValue
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: PatientEncounterType <br>
 * @version generated on Fri Mar 11 09:53:00 PST 2016 by jctoledo
 */

public interface PatientEncounterType extends MedicalQuality {

PatientEncounterTypeValue getPatientEncounterTypeValue();

void setPatientEncounterTypeValue(PatientEncounterTypeValue en);




}