package com.apixio.model.owl.interfaces.donotimplement;

/**
 OWL annotation driven imports 
**/


/**
 * 
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: PreferredProviderOrganizationPlan <br>
 * @version generated on Fri Mar 11 09:53:02 PST 2016 by jctoledo
 */

public interface PreferredProviderOrganizationPlan  extends com.apixio.model.owl.interfaces.InsurancePlan {





}
