package com.apixio.model.owl.interfaces.donotimplement;

/**
 OWL annotation driven imports 
**/
import com.apixio.model.owl.interfaces.donotimplement.ComputationalEntity;


/**
 * 
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: Provenance <br>
 * @version generated on Fri Mar 11 09:53:01 PST 2016 by jctoledo
 */

public interface Provenance  extends ComputationalEntity {





}
