package com.apixio.model.owl.interfaces.donotimplement;

/**
 OWL annotation driven imports 
**/

import java.net.URI;


/**
 * 
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: Rendering <br>
 * @version generated on Fri Mar 11 09:53:02 PST 2016 by jctoledo
 */

public interface Rendering  extends ComputationalEntity, ProvenancedEntity {






}
