package com.apixio.model.owl.interfaces.donotimplement;

/**
 OWL annotation driven imports 
**/

import com.apixio.model.owl.interfaces.donotimplement.ResolutionStatusTypeValue;

/**
 * ResolutionStatusTypeValue
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: ResolutionStatusType <br>
 * @version generated on Fri Mar 11 09:53:00 PST 2016 by jctoledo
 */

public interface ResolutionStatusType extends com.apixio.model.owl.interfaces.donotimplement.MedicalQuality {

ResolutionStatusTypeValue getResolutionStatusTypeValue();

void setResolutionStatusTypeValue(ResolutionStatusTypeValue en);




}