package com.apixio.model.owl.interfaces.donotimplement;

/**
 * RiskAdjustmentInsuranceClaimTypeValue
 * ${dcdescription}
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: ${interfaceName} <br>
 *
 * @version generated on Tue Sep 13 11:58:48 PDT 2016 by jctoledo
 */


public enum RiskAdjustmentInsuranceClaimTypeValue {
    MAO004,
    RAPS
}
