package com.apixio.model.owl.interfaces.donotimplement;

import java.util.Collection;

/**
 OWL annotation driven imports 
**/


/**
 * 
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: SocialQuality <br>
 * @version generated on Fri Mar 11 09:53:02 PST 2016 by jctoledo
 */

public interface SocialQuality  extends InformationalQuality {

    


}
