package com.apixio.model.owl.interfaces.donotimplement;

/**
 * SourceTypeValue
 * <p/>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: ${interfaceName} <br>
 *
 * @version generated on Fri Apr 01 10:02:42 PDT 2016 by jctoledo
 */


public enum SourceTypeValue {
    ASSERTED,
    ASSUMED,
    INFERRED
}
