package com.apixio.model.owl.interfaces.donotimplement;

/**
 * OWL annotation driven imports
 **/

/**
 * SourceTypeValue
 * <p/>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: SourceType <br>
 *
 * @version generated on Fri Apr 01 10:02:42 PDT 2016 by jctoledo
 */

public interface SourceType extends InformationContentQuality {

    SourceTypeValue getSourceTypeValue();

    void setSourceTypeValue(SourceTypeValue en);

     /* ***************************************************
     * Property http://apixio.com/ontology/alo#000218
     */

    /**
     * Gets all property values for the SourceTypeStringValue property.<p>
     *
     *
     * @returns a collection of values for the SourceTypeStringValue property.
     */
    String getSourceTypeStringValue();


    /**
     * Adds a SourceTypeStringValue property value.<p>
     *
     *
     * @param newSourceTypeStringValue the SourceTypeStringValue property value to be added
     */
    void setSourceTypeStringValue(String newSourceTypeStringValue);


}