package com.apixio.model.owl.interfaces.donotimplement;


/**
 * TelephoneTypeValue
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: ${interfaceName} <br>
 * @version generated on Fri Mar 11 09:53:00 PST 2016 by jctoledo
 */


public enum TelephoneTypeValue {
  CELL_PHONE,
HOME_PHONE,
WORK_PHONE
}
