package com.apixio.model.owl.interfaces.donotimplement;

/**
 OWL annotation driven imports 
**/
import com.apixio.model.owl.interfaces.donotimplement.TelephoneTypeValue;

/**
 * TelephoneTypeValue
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: TelephoneType <br>
 * @version generated on Fri Mar 11 09:53:00 PST 2016 by jctoledo
 */

public interface TelephoneType extends com.apixio.model.owl.interfaces.donotimplement.SocialQuality {

TelephoneTypeValue getTelephoneTypeValue();

void setTelephoneTypeValue(TelephoneTypeValue en);




}