package com.apixio.model.owl.interfaces;

import com.apixio.XUUID;
import com.apixio.model.owl.interfaces.donotimplement.AddressType;
import com.apixio.model.owl.interfaces.donotimplement.PositionalIdentifer;

import java.util.Collection;

/**
 * OWL annotation driven imports
 **/


/**
 * 
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: Address <br>
 * @version generated on Mon Apr 04 12:43:22 PDT 2016 by jctoledo
 */

public interface Address  extends PositionalIdentifer {



    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000414
     */

    /**
     * Gets all property values for the AddressType property.<p>
     *
     *
     * @returns a collection of values for the AddressType property.
     */
    AddressType getAddressType();


    /**
     * Adds a AddressType property value.<p>
     *
     *
     * @param newAddressType the AddressType property value to be added
     */
    void setAddressType(AddressType newAddressType);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000404
     */

    /**
     * Gets all property values for the Country property.<p>
     *
     *
     * @returns a collection of values for the Country property.
     */
    String getCountry();


    /**
     * Adds a Country property value.<p>
     *
     *
     * @param newCountry the Country property value to be added
     */
    void setCountry(String newCountry);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000405
     */

    /**
     * Gets all property values for the County property.<p>
     *
     *
     * @returns a collection of values for the County property.
     */
    String getCounty();


    /**
     * Adds a County property value.<p>
     *
     *
     * @param newCounty the County property value to be added
     */
    void setCounty(String newCounty);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000406
     */

    /**
     * Gets all property values for the ZipCode property.<p>
     *
     *
     * @returns a collection of values for the ZipCode property.
     */
    String getZipCode();


    /**
     * Adds a ZipCode property value.<p>
     *
     *
     * @param newZipCode the ZipCode property value to be added
     */
    void setZipCode(String newZipCode);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000407
     */

    /**
     * Gets all property values for the State property.<p>
     *
     *
     * @returns a collection of values for the State property.
     */
    String getState();


    /**
     * Adds a State property value.<p>
     *
     *
     * @param newState the State property value to be added
     */
    void setState(String newState);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000408
     */

    /**
     * Gets all property values for the City property.<p>
     *
     *
     * @returns a collection of values for the City property.
     */
    String getCity();


    /**
     * Adds a City property value.<p>
     *
     *
     * @param newCity the City property value to be added
     */
    void setCity(String newCity);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000409
     */

    /**
     * Gets all property values for the StreetAddresses property.<p>
     *
     * @returns a collection of values for the StreetAddresses property.
     * Collection<? extends String> getStreetAddresses();
     *
     */
    Collection<String> getStreetAddresses();

    /**
     * Add an element to the list
     *
     */
    Collection<String> addStreetAddresses(String anItem);

    /**
     * get element from list by Id
     *
     */
    String getStreetAddressesById(XUUID anID);

    /**
     * Adds a StreetAddresses property value.<p>
     *
     * @param newStreetAddresses the StreetAddresses property value to be added
     * void setStreetAddresses(Collection<? extends String> newStreetAddresses);
     *
     */
    void setStreetAddresses(Collection<String> newStreetAddresses);


}
