package com.apixio.model.owl.interfaces;

import java.util.Collection;

/**
 * OWL annotation driven imports 
**/
import com.apixio.model.owl.interfaces.donotimplement.CodedEntity;
import com.apixio.model.owl.interfaces.donotimplement.MedicalEvent;
import org.joda.time.DateTime;
import java.net.URI;
import com.apixio.XUUID;


/**
 * 
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: Allergy <br>
 * @version generated on Mon Apr 04 12:43:22 PDT 2016 by jctoledo
 */

public interface Allergy  extends CodedEntity, MedicalEvent {

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000004
     */

    /**
     * Gets all property values for the AllergyReactionDate property.<p>
     *
     * @returns a collection of values for the AllergyReactionDate property.
     */
    Date getAllergyReactionDate();


    /**
     * Adds a AllergyReactionDate property value.<p>
     *
     * @param newAllergyReactionDate the AllergyReactionDate property value to be added
     */
    void setAllergyReactionDate(Date newAllergyReactionDate);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000006
     */

    /**
     * Gets all property values for the AllergyResolvedDate property.<p>
     *
     * @returns a collection of values for the AllergyResolvedDate property.
     */
    Date getAllergyResolvedDate();


    /**
     * Adds a AllergyResolvedDate property value.<p>
     *
     * @param newAllergyResolvedDate the AllergyResolvedDate property value to be added
     */
    void setAllergyResolvedDate(Date newAllergyResolvedDate);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000035
     */

    /**
     * Gets all property values for the AllergenCode property.<p>
     *
     * @returns a collection of values for the AllergenCode property.
     */
    ClinicalCode getAllergenCode();


    /**
     * Adds a AllergenCode property value.<p>
     *
     * @param newAllergenCode the AllergenCode property value to be added
     */
    void setAllergenCode(ClinicalCode newAllergenCode);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000480
     */

    /**
     * Gets all property values for the AllergyDiagnosisDate property.<p>
     *
     * @returns a collection of values for the AllergyDiagnosisDate property.
     */
    Date getAllergyDiagnosisDate();


    /**
     * Adds a AllergyDiagnosisDate property value.<p>
     *
     * @param newAllergyDiagnosisDate the AllergyDiagnosisDate property value to be added
     */
    void setAllergyDiagnosisDate(Date newAllergyDiagnosisDate);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000041
     */

    /**
     * Gets all property values for the AllergyAllergenString property.<p>
     *
     * @returns a collection of values for the AllergyAllergenString property.
     */
    String getAllergyAllergenString();


    /**
     * Adds a AllergyAllergenString property value.<p>
     *
     * @param newAllergyAllergenString the AllergyAllergenString property value to be added
     */
    void setAllergyAllergenString(String newAllergyAllergenString);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000483
     */

    /**
     * Gets all property values for the AllergyReactionSeverity property.<p>
     *
     * @returns a collection of values for the AllergyReactionSeverity property.
     */
    String getAllergyReactionSeverity();


    /**
     * Adds a AllergyReactionSeverity property value.<p>
     *
     * @param newAllergyReactionSeverity the AllergyReactionSeverity property value to be added
     */
    void setAllergyReactionSeverity(String newAllergyReactionSeverity);



}
