package com.apixio.model.owl.interfaces;

/**
 * OWL annotation driven imports
 **/

import com.apixio.model.owl.interfaces.donotimplement.BiologicalEntity;
import com.apixio.model.owl.interfaces.donotimplement.CodedEntity;


/**
 * <p/>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: AnatomicalEntity <br>
 *
 * @version generated on Fri Mar 11 09:53:01 PST 2016 by jctoledo
 */

public interface AnatomicalEntity extends CodedEntity, BiologicalEntity {



    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000350
     */

    /**
     * Gets all property values for the AnatomicalEntityName property.<p>
     *
     * @returns a collection of values for the AnatomicalEntityName property.
     */
    String getAnatomicalEntityName();


    /**
     * Adds a AnatomicalEntityName property value.<p>
     *
     * @param newAnatomicalEntityName the AnatomicalEntityName property value to be added
     */
    void setAnatomicalEntityName(String newAnatomicalEntityName);



}
