package com.apixio.model.owl.interfaces;

/**
 * OWL annotation driven imports
 **/

import com.apixio.model.owl.interfaces.donotimplement.CodedEntity;
import com.apixio.model.owl.interfaces.donotimplement.DimensionalQuantity;


/**
 *
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: BiometricValue <br>
 * @version generated on Fri Mar 11 09:53:02 PST 2016 by jctoledo
 */

public interface BiometricValue extends CodedEntity, DimensionalQuantity {



    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000477
     */

    /**
     * Gets all property values for the MeasurmentResultDate property.<p>
     *
     * @returns a collection of values for the MeasurmentResultDate property.
     */
    Date getMeasurmentResultDate();


    /**
     * Adds a MeasurmentResultDate property value.<p>
     *
     * @param newMeasurmentResultDate the MeasurmentResultDate property value to be added
     */
    void setMeasurmentResultDate(Date newMeasurmentResultDate);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000010
     */

    /**
     * Gets all property values for the MeasurmentUnit property.<p>
     *
     * @returns a collection of values for the MeasurmentUnit property.
     */
    String getMeasurmentUnit();


    /**
     * Adds a MeasurmentUnit property value.<p>
     *
     * @param newMeasurmentUnit the MeasurmentUnit property value to be added
     */
    void setMeasurmentUnit(String newMeasurmentUnit);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000023
     */

    /**
     * Gets all property values for the BiometricValueString property.<p>
     *
     * @returns a collection of values for the BiometricValueString property.
     */
    String getBiometricValueString();


    /**
     * Adds a BiometricValueString property value.<p>
     *
     * @param newBiometricValueString the BiometricValueString property value to be added
     */
    void setBiometricValueString(String newBiometricValueString);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000475
     */

    /**
     * Gets all property values for the BiometricValueName property.<p>
     *
     * @returns a collection of values for the BiometricValueName property.
     */
    String getBiometricValueName();


    /**
     * Adds a BiometricValueName property value.<p>
     *
     * @param newBiometricValueName the BiometricValueName property value to be added
     */
    void setBiometricValueName(String newBiometricValueName);


}
