package com.apixio.model.owl.interfaces;

/**
 * OWL annotation driven imports
 **/

import com.apixio.model.owl.interfaces.donotimplement.CareSiteType;
import com.apixio.model.owl.interfaces.donotimplement.ProvenancedEntity;
import com.apixio.model.owl.interfaces.donotimplement.SocialEntity;

import java.net.URI;


/**
 *
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: CareSite <br>
 * @version generated on Fri Mar 11 09:53:02 PST 2016 by jctoledo
 */

public interface CareSite extends ProvenancedEntity, SocialEntity {



    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000155
     */

    /**
     * Gets all property values for the NationalProviderIdentifier property.<p>
     *
     * @returns a collection of values for the NationalProviderIdentifier property.
     */
    ExternalIdentifier getNationalProviderIdentifier();


    /**
     * Adds a NationalProviderIdentifier property value.<p>
     *
     * @param newNationalProviderIdentifier the NationalProviderIdentifier property value to be added
     */
    void setNationalProviderIdentifier(ExternalIdentifier newNationalProviderIdentifier);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000415
     */

    /**
     * Gets all property values for the PrimaryAddress property.<p>
     *
     * @returns a collection of values for the PrimaryAddress property.
     */
    Address getPrimaryAddress();


    /**
     * Adds a PrimaryAddress property value.<p>
     *
     * @param newPrimaryAddress the PrimaryAddress property value to be added
     */
    void setPrimaryAddress(Address newPrimaryAddress);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#810018
     */

    /**
     * Gets all property values for the CareSiteType property.<p>
     *
     * @returns a collection of values for the CareSiteType property.
     */
    CareSiteType getCareSiteType();


    /**
     * Adds a CareSiteType property value.<p>
     *
     * @param newCareSiteType the CareSiteType property value to be added
     */
    void setCareSiteType(CareSiteType newCareSiteType);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000463
     */

    /**
     * Gets all property values for the CareSiteName property.<p>
     *
     * @returns a collection of values for the CareSiteName property.
     */
    String getCareSiteName();


    /**
     * Adds a CareSiteName property value.<p>
     *
     * @param newCareSiteName the CareSiteName property value to be added
     */
    void setCareSiteName(String newCareSiteName);


}
