package com.apixio.model.owl.interfaces;

/**
 OWL annotation driven imports 
**/


import com.apixio.model.owl.interfaces.donotimplement.MedicalCodeEntity;

/**
 * 
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: ClinicalCode <br>
 * @version generated on Fri Mar 11 09:53:02 PST 2016 by jctoledo
 */

public interface ClinicalCode  extends MedicalCodeEntity {



    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000401
     */

    /**
     * Gets all property values for the ClinicalCodingSystem property.<p>
     *
     * @returns a collection of values for the ClinicalCodingSystem property.
     */
    ClinicalCodingSystem getClinicalCodingSystem();


    /**
     * Adds a ClinicalCodingSystem property value.<p>
     *
     * @param newClinicalCodingSystem the ClinicalCodingSystem property value to be added
     */
    void setClinicalCodingSystem(ClinicalCodingSystem newClinicalCodingSystem);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000012
     */

    /**
     * Gets all property values for the ClinicalCodeDisplayName property.<p>
     *
     * @returns a collection of values for the ClinicalCodeDisplayName property.
     */
    String getClinicalCodeDisplayName();


    /**
     * Adds a ClinicalCodeDisplayName property value.<p>
     *
     * @param newClinicalCodeDisplayName the ClinicalCodeDisplayName property value to be added
     */
    void setClinicalCodeDisplayName(String newClinicalCodeDisplayName);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000400
     */

    /**
     * Gets all property values for the ClinicalCodeValue property.<p>
     *
     * @returns a collection of values for the ClinicalCodeValue property.
     */
    String getClinicalCodeValue();


    /**
     * Adds a ClinicalCodeValue property value.<p>
     *
     * @param newClinicalCodeValue the ClinicalCodeValue property value to be added
     */
    void setClinicalCodeValue(String newClinicalCodeValue);



}
