package com.apixio.model.owl.interfaces;

import com.apixio.XUUID;
import com.apixio.model.owl.interfaces.donotimplement.SoftwareEntity;

import java.util.Collection;

/**
 * OWL annotation driven imports
 **/


/**
 * 
 * The collection of annotations made by CMS when during the RAPS or EDPS validation procedures
	*
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: CMSClaimValidationResult <br>
 * @version generated on Wed Jun 08 11:20:18 PDT 2016 by jctoledo
 */

public interface CMSClaimValidationResult  extends SoftwareEntity {



    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000200
     */

    /**
     * Gets all property values for the ClaimOverpaymentIdentifier property.<p>
     *
     *
     * @returns a collection of values for the ClaimOverpaymentIdentifier property.
     */
    ExternalIdentifier getClaimOverpaymentIdentifier();


    /**
     * Adds a ClaimOverpaymentIdentifier property value.<p>
     *
     *
     * @param newClaimOverpaymentIdentifier the ClaimOverpaymentIdentifier property value to be added
     */
    void setClaimOverpaymentIdentifier(ExternalIdentifier newClaimOverpaymentIdentifier);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000212
     */

    /**
     * Gets all property values for the ValidatedClaimTransactionDate property.<p>
     *
     *
     * @returns a collection of values for the ValidatedClaimTransactionDate property.
     */
    Date getValidatedClaimTransactionDate();


    /**
     * Adds a ValidatedClaimTransactionDate property value.<p>
     *
     *
     * @param newValidatedClaimTransactionDate the ValidatedClaimTransactionDate property value to be added
     */
    void setValidatedClaimTransactionDate(Date newValidatedClaimTransactionDate);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000249
     */

    /**
     * Gets all property values for the CMSValidationErrors property.<p>
     *
     * @returns a collection of values for the CMSValidationErrors property.
     * Collection<? extends CMSValidationError> getCMSValidationErrors();
     *
     */
    Collection<CMSValidationError> getCMSValidationErrors();

    /**
     * Add an element to the list
     *
     */
    Collection<CMSValidationError> addCMSValidationErrors(CMSValidationError anItem);

    /**
     * get element from list by Id
     *
     */
    CMSValidationError getCMSValidationErrorsById(XUUID anID);

    /**
     * Adds a CMSValidationErrors property value.<p>
     *
     * @param newCMSValidationErrors the CMSValidationErrors property value to be added
     * void setCMSValidationErrors(Collection<? extends CMSValidationError> newCMSValidationErrors);
     *
     */
    void setCMSValidationErrors(Collection<CMSValidationError> newCMSValidationErrors);
    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000244
     */

    /**
     * Gets all property values for the ValidatedClaimPaymentYear property.<p>
     *
     *
     * @returns a collection of values for the ValidatedClaimPaymentYear property.
     */
    String getValidatedClaimPaymentYear();


    /**
     * Adds a ValidatedClaimPaymentYear property value.<p>
     *
     *
     * @param newValidatedClaimPaymentYear the ValidatedClaimPaymentYear property value to be added
     */
    void setValidatedClaimPaymentYear(String newValidatedClaimPaymentYear);


    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000245
     */

    /**
     * Gets all property values for the ValidatedClaimControlNumber property.<p>
     *
     *
     * @returns a collection of values for the ValidatedClaimControlNumber property.
     */
    String getValidatedClaimControlNumber();


    /**
     * Adds a ValidatedClaimControlNumber property value.<p>
     *
     *
     * @param newValidatedClaimControlNumber the ValidatedClaimControlNumber property value to be added
     */
    void setValidatedClaimControlNumber(String newValidatedClaimControlNumber);


    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000246
     */

    /**
     * Gets all property values for the ValidatedClaimPatientDateOfBirth property.<p>
     *
     *
     * @returns a collection of values for the ValidatedClaimPatientDateOfBirth property.
     */
    String getValidatedClaimPatientDateOfBirth();


    /**
     * Adds a ValidatedClaimPatientDateOfBirth property value.<p>
     *
     *
     * @param newValidatedClaimPatientDateOfBirth the ValidatedClaimPatientDateOfBirth property value to be added
     */
    void setValidatedClaimPatientDateOfBirth(String newValidatedClaimPatientDateOfBirth);


    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000247
     */

    /**
     * Gets all property values for the ValidatedClaimProviderType property.<p>
     *
     *
     * @returns a collection of values for the ValidatedClaimProviderType property.
     */
    String getValidatedClaimProviderType();


    /**
     * Adds a ValidatedClaimProviderType property value.<p>
     *
     *
     * @param newValidatedClaimProviderType the ValidatedClaimProviderType property value to be added
     */
    void setValidatedClaimProviderType(String newValidatedClaimProviderType);


    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000248
     */

    /**
     * Gets all property values for the RiskAssessmentCodeClusters property.<p>
     *
     *
     * @returns a collection of values for the RiskAssessmentCodeClusters property.
     */
    String getRiskAssessmentCodeClusters();


    /**
     * Adds a RiskAssessmentCodeClusters property value.<p>
     *
     *
     * @param newRiskAssessmentCodeClusters the RiskAssessmentCodeClusters property value to be added
     */
    void setRiskAssessmentCodeClusters(String newRiskAssessmentCodeClusters);


    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000251
     */

    /**
     * Gets all property values for the ValidatedClaimFileMode property.<p>
     *
     *
     * @returns a collection of values for the ValidatedClaimFileMode property.
     */
    String getValidatedClaimFileMode();


    /**
     * Adds a ValidatedClaimFileMode property value.<p>
     *
     *
     * @param newValidatedClaimFileMode the ValidatedClaimFileMode property value to be added
     */
    void setValidatedClaimFileMode(String newValidatedClaimFileMode);


    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000252
     */

    /**
     * Gets all property values for the ValidatedClaimPlanNumber property.<p>
     *
     *
     * @returns a collection of values for the ValidatedClaimPlanNumber property.
     */
    String getValidatedClaimPlanNumber();


    /**
     * Adds a ValidatedClaimPlanNumber property value.<p>
     *
     *
     * @param newValidatedClaimPlanNumber the ValidatedClaimPlanNumber property value to be added
     */
    void setValidatedClaimPlanNumber(String newValidatedClaimPlanNumber);
}
