package com.apixio.model.owl.interfaces;

import java.util.Collection;
import com.apixio.XUUID;

/**
 OWL annotation driven imports 
**/
import com.apixio.model.owl.interfaces.donotimplement.InformationalEntityIdentifier;


/**
 * 
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: ContactDetails <br>
 * @version generated on Fri Mar 11 09:53:02 PST 2016 by jctoledo
 */

public interface ContactDetails  extends InformationalEntityIdentifier {



    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000415
     */

    /**
     * Gets all property values for the PrimaryAddress property.<p>
     *
     * @returns a collection of values for the PrimaryAddress property.
     */
    Address getPrimaryAddress();


    /**
     * Adds a PrimaryAddress property value.<p>
     *
     * @param newPrimaryAddress the PrimaryAddress property value to be added
     */
    void setPrimaryAddress(Address newPrimaryAddress);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000416
     */

    /**
     * Gets all property values for the AlternateAddresses property.<p>
     *
     * @returns a collection of values for the AlternateAddresses property.
     * Collection<? extends Address> getAlternateAddresses();
     */
    Collection<Address> getAlternateAddresses();

    /**
     * Add an element to the list
     */
    Collection<Address> addAlternateAddresses(Address anItem);

    /**
     * get element from list by Id
     */
    Address getAlternateAddressesById(XUUID anID);

    /**
     * Adds a AlternateAddresses property value.<p>
     *
     * @param newAlternateAddresses the AlternateAddresses property value to be added
     * void setAlternateAddresses(Collection<? extends Address> newAlternateAddresses);
     */
    void setAlternateAddresses(Collection<Address> newAlternateAddresses);
    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000420
     */

    /**
     * Gets all property values for the TelephoneNumber property.<p>
     *
     * @returns a collection of values for the TelephoneNumber property.
     */
    TelephoneNumber getTelephoneNumber();


    /**
     * Adds a TelephoneNumber property value.<p>
     *
     * @param newTelephoneNumber the TelephoneNumber property value to be added
     */
    void setTelephoneNumber(TelephoneNumber newTelephoneNumber);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000426
     */

    /**
     * Gets all property values for the AlternateTelephoneNumbers property.<p>
     *
     * @returns a collection of values for the AlternateTelephoneNumbers property.
     * Collection<? extends TelephoneNumber> getAlternateTelephoneNumbers();
     */
    Collection<TelephoneNumber> getAlternateTelephoneNumbers();

    /**
     * Add an element to the list
     */
    Collection<TelephoneNumber> addAlternateTelephoneNumbers(TelephoneNumber anItem);

    /**
     * get element from list by Id
     */
    TelephoneNumber getAlternateTelephoneNumbersById(XUUID anID);

    /**
     * Adds a AlternateTelephoneNumbers property value.<p>
     *
     * @param newAlternateTelephoneNumbers the AlternateTelephoneNumbers property value to be added
     * void setAlternateTelephoneNumbers(Collection<? extends TelephoneNumber> newAlternateTelephoneNumbers);
     */
    void setAlternateTelephoneNumbers(Collection<TelephoneNumber> newAlternateTelephoneNumbers);
    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000421
     */

    /**
     * Gets all property values for the PrimaryEmailAddress property.<p>
     *
     * @returns a collection of values for the PrimaryEmailAddress property.
     */
    String getPrimaryEmailAddress();


    /**
     * Adds a PrimaryEmailAddress property value.<p>
     *
     * @param newPrimaryEmailAddress the PrimaryEmailAddress property value to be added
     */
    void setPrimaryEmailAddress(String newPrimaryEmailAddress);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000422
     */

    /**
     * Gets all property values for the AlternateEmailAddresses property.<p>
     *
     * @returns a collection of values for the AlternateEmailAddresses property.
     * Collection<? extends String> getAlternateEmailAddresses();
     */
    Collection<String> getAlternateEmailAddresses();

    /**
     * Add an element to the list
     */
    Collection<String> addAlternateEmailAddresses(String anItem);

    /**
     * get element from list by Id
     */
    String getAlternateEmailAddressesById(XUUID anID);

    /**
     * Adds a AlternateEmailAddresses property value.<p>
     *
     * @param newAlternateEmailAddresses the AlternateEmailAddresses property value to be added
     * void setAlternateEmailAddresses(Collection<? extends String> newAlternateEmailAddresses);
     */
    void setAlternateEmailAddresses(Collection<String> newAlternateEmailAddresses);



}
