package com.apixio.model.owl.interfaces;

/**
 OWL annotation driven imports 
**/
import com.apixio.model.owl.interfaces.donotimplement.ApixioDate;


/**
 * 
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: DateRange <br>
 * @version generated on Fri Mar 11 09:53:01 PST 2016 by jctoledo
 */

public interface DateRange  extends ApixioDate {


    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000377
     */

    /**
     * Gets all property values for the StartDate property.<p>
     *
     * @returns a collection of values for the StartDate property.
     */
    Date getStartDate();


    /**
     * Adds a StartDate property value.<p>
     *
     * @param newStartDate the StartDate property value to be added
     */
    void setStartDate(Date newStartDate);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000378
     */

    /**
     * Gets all property values for the EndDate property.<p>
     *
     * @returns a collection of values for the EndDate property.
     */
    Date getEndDate();


    /**
     * Adds a EndDate property value.<p>
     *
     * @param newEndDate the EndDate property value to be added
     */
    void setEndDate(Date newEndDate);


}
