package com.apixio.model.owl.interfaces;

/**
 OWL annotation driven imports 
**/
import com.apixio.model.owl.interfaces.donotimplement.ApixioDate;
import org.joda.time.DateTime;


/**
 * 
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: Date <br>
 * @version generated on Fri Mar 11 09:53:02 PST 2016 by jctoledo
 */

public interface Date  extends ApixioDate {





    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000109
     */

    /**
     * Gets all property values for the DateValue property.<p>
     *
     * @returns a collection of values for the DateValue property.
     */
    DateTime getDateValue();


    /**
     * Adds a DateValue property value.<p>
     *
     * @param newDateValue the DateValue property value to be added
     */
    void setDateValue(DateTime newDateValue);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000311
     */

    /**
     * Gets all property values for the TimeZone property.<p>
     *
     * @returns a collection of values for the TimeZone property.
     */
    String getTimeZone();


    /**
     * Adds a TimeZone property value.<p>
     *
     * @param newTimeZone the TimeZone property value to be added
     */
    void setTimeZone(String newTimeZone);


}
