package com.apixio.model.owl.interfaces;

import java.util.Collection;

/**
 OWL annotation driven imports 
**/
import com.apixio.XUUID;
import com.apixio.model.owl.interfaces.donotimplement.GenderType;
import com.apixio.model.owl.interfaces.donotimplement.MaritalStatusType;
import com.apixio.model.owl.interfaces.donotimplement.MedicalEntity;
import com.apixio.model.owl.interfaces.donotimplement.ProvenancedEntity;

import java.net.URI;


/**
 * 
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: Demographics <br>
 * @version generated on Fri Mar 11 09:53:01 PST 2016 by jctoledo
 */

public interface Demographics  extends ProvenancedEntity, MedicalEntity {



    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000015
     */

    /**
     * Gets all property values for the GenderType property.<p>
     *
     * @returns a collection of values for the GenderType property.
     */
    GenderType getGenderType();


    /**
     * Adds a GenderType property value.<p>
     *
     * @param newGenderType the GenderType property value to be added
     */
    void setGenderType(GenderType newGenderType);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000062
     */

    /**
     * Gets all property values for the Name property.<p>
     *
     * @returns a collection of values for the Name property.
     */
    Name getName();


    /**
     * Adds a Name property value.<p>
     *
     * @param newName the Name property value to be added
     */
    void setName(Name newName);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000085
     */

    /**
     * Gets all property values for the AlternateNames property.<p>
     *
     * @returns a collection of values for the AlternateNames property.
     * Collection<? extends Name> getAlternateNames();
     */
    Collection<Name> getAlternateNames();

    /**
     * Add an element to the list
     */
    Collection<Name> addAlternateNames(Name anItem);

    /**
     * get element from list by Id
     */
    Name getAlternateNamesById(XUUID anID);

    /**
     * Adds a AlternateNames property value.<p>
     *
     * @param newAlternateNames the AlternateNames property value to be added
     * void setAlternateNames(Collection<? extends Name> newAlternateNames);
     */
    void setAlternateNames(Collection<Name> newAlternateNames);
    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000346
     */

    /**
     * Gets all property values for the MaritalStatusType property.<p>
     *
     * @returns a collection of values for the MaritalStatusType property.
     */
    MaritalStatusType getMaritalStatusType();


    /**
     * Adds a MaritalStatusType property value.<p>
     *
     * @param newMaritalStatusType the MaritalStatusType property value to be added
     */
    void setMaritalStatusType(MaritalStatusType newMaritalStatusType);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000383
     */

    /**
     * Gets all property values for the DateOfBirth property.<p>
     *
     * @returns a collection of values for the DateOfBirth property.
     */
    Date getDateOfBirth();


    /**
     * Adds a DateOfBirth property value.<p>
     *
     * @param newDateOfBirth the DateOfBirth property value to be added
     */
    void setDateOfBirth(Date newDateOfBirth);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000384
     */

    /**
     * Gets all property values for the DateOfDeath property.<p>
     *
     * @returns a collection of values for the DateOfDeath property.
     */
    Date getDateOfDeath();


    /**
     * Adds a DateOfDeath property value.<p>
     *
     * @param newDateOfDeath the DateOfDeath property value to be added
     */
    void setDateOfDeath(Date newDateOfDeath);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000429
     */

    /**
     * Gets all property values for the Race property.<p>
     *
     * @returns a collection of values for the Race property.
     */
    ClinicalCode getRace();


    /**
     * Adds a Race property value.<p>
     *
     * @param newRace the Race property value to be added
     */
    void setRace(ClinicalCode newRace);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000430
     */

    /**
     * Gets all property values for the Ethnicity property.<p>
     *
     * @returns a collection of values for the Ethnicity property.
     */
    ClinicalCode getEthnicity();


    /**
     * Adds a Ethnicity property value.<p>
     *
     * @param newEthnicity the Ethnicity property value to be added
     */
    void setEthnicity(ClinicalCode newEthnicity);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000014
     */

    /**
     * Gets all property values for the ReligiousAffiliation property.<p>
     *
     * @returns a collection of values for the ReligiousAffiliation property.
     */
    String getReligiousAffiliation();


    /**
     * Adds a ReligiousAffiliation property value.<p>
     *
     * @param newReligiousAffiliation the ReligiousAffiliation property value to be added
     */
    void setReligiousAffiliation(String newReligiousAffiliation);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000368
     */

    /**
     * Gets all property values for the Languages property.<p>
     *
     * @returns a collection of values for the Languages property.
     * Collection<? extends String> getLanguages();
     */
    Collection<String> getLanguages();

    /**
     * Add an element to the list
     */
    Collection<String> addLanguages(String anItem);

    /**
     * get element from list by Id
     */
    String getLanguagesById(XUUID anID);

    /**
     * Adds a Languages property value.<p>
     *
     * @param newLanguages the Languages property value to be added
     * void setLanguages(Collection<? extends String> newLanguages);
     */
    void setLanguages(Collection<String> newLanguages);



}
