package com.apixio.model.owl.interfaces;

import com.apixio.XUUID;
import com.apixio.model.owl.interfaces.donotimplement.ApixioDate;
import com.apixio.model.owl.interfaces.donotimplement.Human;
import com.apixio.model.owl.interfaces.donotimplement.ProvenancedEntity;
import com.apixio.model.owl.interfaces.donotimplement.TextualEntity;

import java.net.URI;
import java.util.Collection;

/**
 * OWL annotation driven imports
 **/


/**
 * <p/>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: Document <br>
 *
 * @version generated on Fri Mar 11 09:53:00 PST 2016 by jctoledo
 */

public interface Document extends ProvenancedEntity, TextualEntity {




    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000077
     */

    /**
     * Gets all property values for the DocumentAuthors property.<p>
     *
     * @returns a collection of values for the DocumentAuthors property.
     * Collection<? extends MedicalProfessional> getDocumentAuthors();
     * the medical professional who is originator or creator of a document or medical note
     *
     */
    Collection<MedicalProfessional> getDocumentAuthors();

    /**
     * Add an element to the list
     * the medical professional who is originator or creator of a document or medical note
     *
     */
    Collection<MedicalProfessional> addDocumentAuthors(MedicalProfessional anItem);

    /**
     * get element from list by Id
     * the medical professional who is originator or creator of a document or medical note
     *
     */
    MedicalProfessional getDocumentAuthorsById(XUUID anID);

    /**
     * Adds a DocumentAuthors property value.<p>
     *
     * @param newDocumentAuthors the DocumentAuthors property value to be added
     * void setDocumentAuthors(Collection<? extends MedicalProfessional> newDocumentAuthors);
     * the medical professional who is originator or creator of a document or medical note
     *
     */
    void setDocumentAuthors(Collection<MedicalProfessional> newDocumentAuthors);
    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000083
     */

    /**
     * Gets all property values for the DocumentCareSite property.<p>
     *
     * @returns a collection of values for the DocumentCareSite property.
     */
    CareSite getDocumentCareSite();


    /**
     * Adds a DocumentCareSite property value.<p>
     *
     * @param newDocumentCareSite the DocumentCareSite property value to be added
     */
    void setDocumentCareSite(CareSite newDocumentCareSite);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000143
     */

    /**
     * Gets all property values for the DocumentPages property.<p>
     *
     * @returns a collection of values for the DocumentPages property.
     * Collection<? extends Page> getDocumentPages();
     */
    Collection<Page> getDocumentPages();

    /**
     * Add an element to the list
     */
    Collection<Page> addDocumentPages(Page anItem);

    /**
     * get element from list by Id
     */
    Page getDocumentPagesById(XUUID anID);

    /**
     * Adds a DocumentPages property value.<p>
     *
     * @param newDocumentPages the DocumentPages property value to be added
     * void setDocumentPages(Collection<? extends Page> newDocumentPages);
     */
    void setDocumentPages(Collection<Page> newDocumentPages);
    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000367
     */

    /**
     * Gets all property values for the DocumentDate property.<p>
     *
     * @returns a collection of values for the DocumentDate property.
     */
    ApixioDate getDocumentDate();


    /**
     * Adds a DocumentDate property value.<p>
     *
     * @param newDocumentDate the DocumentDate property value to be added
     */
    void setDocumentDate(ApixioDate newDocumentDate);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000136
     */

    /**
     * Gets all property values for the Title property.<p>
     *
     * @returns a collection of values for the Title property.
     */
    String getTitle();


    /**
     * Adds a Title property value.<p>
     *
     * @param newTitle the Title property value to be added
     */
    void setTitle(String newTitle);


}
