package com.apixio.model.owl.interfaces;

import java.util.Collection;

/**
 * OWL annotation driven imports 
**/
import org.joda.time.DateTime;
import java.net.URI;
import com.apixio.XUUID;


/**
 * 
 * 
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: EDPSValidationError <br>
 * @version generated on Wed Jun 08 11:20:18 PDT 2016 by jctoledo
 */

public interface EDPSValidationError  extends CMSValidationError {





}
