package com.apixio.model.owl.interfaces;

import java.util.Collection;

/**
 OWL annotation driven imports 
**/
import org.joda.time.DateTime;
import java.net.URI;
import com.apixio.XUUID;


/**
 * 
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: EncounterDocument <br>
 * @version generated on Thu Mar 31 15:40:44 PDT 2016 by jctoledo
 */

public interface EncounterDocument  extends Document {



    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000172
     */

    /**
     * Gets all property values for the SignatureDate property.<p>
     *
     * @returns a collection of values for the SignatureDate property.
     */
    Date getSignatureDate();


    /**
     * Adds a SignatureDate property value.<p>
     *
     * @param newSignatureDate the SignatureDate property value to be added
     */
    void setSignatureDate(Date newSignatureDate);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000169
     */

    /**
     * Gets all property values for the SignedStatus property.<p>
     *
     * @returns a collection of values for the SignedStatus property.
     */
    Boolean getSignedStatus();




    /**
     * Adds a SignedStatus property value.<p>
     *
     * @param newSignedStatus the SignedStatus property value to be added
     */
    void setSignedStatus(Boolean newSignedStatus);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000183
     */

    /**
     * Gets all property values for the PatientEncounterURI property.<p>
     *
     * @returns a collection of values for the PatientEncounterURI property.
     */
    URI getPatientEncounterURI();


    /**
     * Adds a PatientEncounterURI property value.<p>
     *
     * @param newPatientEncounterURI the PatientEncounterURI property value to be added
     */
    void setPatientEncounterURI(URI newPatientEncounterURI);



}
