package com.apixio.model.owl.interfaces;

/**
 * OWL annotation driven imports
 **/

import com.apixio.model.owl.interfaces.donotimplement.InformationalEntityIdentifier;


/**
 *
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: ExternalIdentifier <br>
 * @version generated on Fri Mar 11 09:53:01 PST 2016 by jctoledo
 */

public interface ExternalIdentifier extends InformationalEntityIdentifier {

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000151
     */

    /**
     * Gets all property values for the IDValue property.<p>
     *
     * @returns a collection of values for the IDValue property.
     */
    String getIDValue();


    /**
     * Adds a IDValue property value.<p>
     *
     * @param newIDValue the IDValue property value to be added
     */
    void setIDValue(String newIDValue);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000152
     */

    /**
     * Gets all property values for the IDType property.<p>
     *
     * @returns a collection of values for the IDType property.
     */
    String getIDType();


    /**
     * Adds a IDType property value.<p>
     *
     * @param newIDType the IDType property value to be added
     */
    void setIDType(String newIDType);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000153
     */

    /**
     * Gets all property values for the AssignAuthority property.<p>
     *
     * @returns a collection of values for the AssignAuthority property.
     */
    String getAssignAuthority();


    /**
     * Adds a AssignAuthority property value.<p>
     *
     * @param newAssignAuthority the AssignAuthority property value to be added
     */
    void setAssignAuthority(String newAssignAuthority);

}
