package com.apixio.model.owl.interfaces;

/**
 OWL annotation driven imports 
**/
import com.apixio.model.owl.interfaces.donotimplement.ComputationalEntity;
import com.apixio.model.owl.interfaces.donotimplement.ProvenancedEntity;

import java.net.URI;


/**
 * 
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: File <br>
 * @version generated on Fri Mar 11 09:53:00 PST 2016 by jctoledo
 */

public interface File  extends ComputationalEntity, ProvenancedEntity {



    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000068
     */

    /**
     * Gets all property values for the FileDate property.<p>
     *
     * @returns a collection of values for the FileDate property.
     */
    Date getFileDate();


    /**
     * Adds a FileDate property value.<p>
     *
     * @param newFileDate the FileDate property value to be added
     */
    void setFileDate(Date newFileDate);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000034
     */

    /**
     * Gets all property values for the MIMEType property.<p>
     *
     * @returns a collection of values for the MIMEType property.
     */
    String getMIMEType();


    /**
     * Adds a MIMEType property value.<p>
     *
     * @param newMIMEType the MIMEType property value to be added
     */
    void setMIMEType(String newMIMEType);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000105
     */

    /**
     * Gets all property values for the Hash property.<p>
     *
     * @returns a collection of values for the Hash property.
     */
    String getHash();


    /**
     * Adds a Hash property value.<p>
     *
     * @param newHash the Hash property value to be added
     */
    void setHash(String newHash);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000337
     */

    /**
     * Gets all property values for the FileURL property.<p>
     *
     * @returns a collection of values for the FileURL property.
     */
    URI getFileURL();


    /**
     * Adds a FileURL property value.<p>
     *
     * @param newFileURL the FileURL property value to be added
     */
    void setFileURL(URI newFileURL);



}
