package com.apixio.model.owl.interfaces;

/**
 OWL annotation driven imports 
**/

import java.net.URI;


/**
 * 
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: HICN <br>
 * @version generated on Fri Mar 11 09:53:02 PST 2016 by jctoledo
 */

public interface HICN  extends TimeBoundExternalIdentifier {



    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000454
     */

    /**
     * Gets all property values for the MedicarePlanURI property.<p>
     *
     * @returns a collection of values for the MedicarePlanURI property.
     */
    URI getMedicarePlanURI();


    /**
     * Adds a MedicarePlanURI property value.<p>
     *
     * @param newMedicarePlanURI the MedicarePlanURI property value to be added
     */
    void setMedicarePlanURI(URI newMedicarePlanURI);




}
