package com.apixio.model.owl.interfaces;

/**
 OWL annotation driven imports 
**/
import com.apixio.model.owl.interfaces.donotimplement.Rendering;

        import java.net.URI;


/**
 * 
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: ImageRendering <br>
 * @version generated on Fri Mar 11 09:53:02 PST 2016 by jctoledo
 */

public interface ImageRendering  extends Rendering {




    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000173
     */

    /**
     * Gets all property values for the ImageResolution property.<p>
     *
     * @returns a collection of values for the ImageResolution property.
     */
    String getImageResolution();


    /**
     * Adds a ImageResolution property value.<p>
     *
     * @param newImageResolution the ImageResolution property value to be added
     */
    void setImageResolution(String newImageResolution);



}
