package com.apixio.model.owl.interfaces;

import java.net.URI;
import java.util.Collection;

/**
 OWL annotation driven imports 
**/
import com.apixio.model.owl.interfaces.donotimplement.CodedEntity;
import com.apixio.model.owl.interfaces.donotimplement.Corporation;
import com.apixio.model.owl.interfaces.donotimplement.InsuranceClaimStatusType;


/**
 * 
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: InsuranceCompany <br>
 * @version generated on Fri Mar 11 09:53:02 PST 2016 by jctoledo
 */

public interface InsuranceCompany  extends Corporation {



}
