package com.apixio.model.owl.interfaces;

/**
 * OWL annotation driven imports
 **/

import com.apixio.model.owl.interfaces.donotimplement.CodedEntity;
import com.apixio.model.owl.interfaces.donotimplement.DimensionalQuantity;
import com.apixio.model.owl.interfaces.donotimplement.LabFlagType;


/**
 * <p/>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: LabResult <br>
 *
 * @version generated on Fri Mar 11 09:53:02 PST 2016 by jctoledo
 */

public interface LabResult extends CodedEntity, DimensionalQuantity {


    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000021
     */

    /**
     * Gets all property values for the LabFlagType property.<p>
     *
     * @returns a collection of values for the LabFlagType property.
     */
    LabFlagType getLabFlagType();


    /**
     * Adds a LabFlagType property value.<p>
     *
     * @param newLabFlagType the LabFlagType property value to be added
     */
    void setLabFlagType(LabFlagType newLabFlagType);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000022
     */

    /**
     * Gets all property values for the LabResultSampleDate property.<p>
     *
     * @returns a collection of values for the LabResultSampleDate property.
     */
    Date getLabResultSampleDate();


    /**
     * Adds a LabResultSampleDate property value.<p>
     *
     * @param newLabResultSampleDate the LabResultSampleDate property value to be added
     */
    void setLabResultSampleDate(Date newLabResultSampleDate);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000069
     */

    /**
     * Gets all property values for the LabResultCareSite property.<p>
     *
     * @returns a collection of values for the LabResultCareSite property.
     */
    CareSite getLabResultCareSite();


    /**
     * Adds a LabResultCareSite property value.<p>
     *
     * @param newLabResultCareSite the LabResultCareSite property value to be added
     */
    void setLabResultCareSite(CareSite newLabResultCareSite);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000489
     */

    /**
     * Gets all property values for the Specimen property.<p>
     *
     * @returns a collection of values for the Specimen property.
     */
    ClinicalCode getSpecimen();


    /**
     * Adds a Specimen property value.<p>
     *
     * @param newSpecimen the Specimen property value to be added
     */
    void setSpecimen(ClinicalCode newSpecimen);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000490
     */

    /**
     * Gets all property values for the LabPanel property.<p>
     *
     * @returns a collection of values for the LabPanel property.
     */
    ClinicalCode getLabPanel();


    /**
     * Adds a LabPanel property value.<p>
     *
     * @param newLabPanel the LabPanel property value to be added
     */
    void setLabPanel(ClinicalCode newLabPanel);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000492
     */

    /**
     * Gets all property values for the LabSuperPanel property.<p>
     *
     * @returns a collection of values for the LabSuperPanel property.
     */
    ClinicalCode getLabSuperPanel();


    /**
     * Adds a LabSuperPanel property value.<p>
     *
     * @param newLabSuperPanel the LabSuperPanel property value to be added
     */
    void setLabSuperPanel(ClinicalCode newLabSuperPanel);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000494
     */

    /**
     * Gets all property values for the SampleDate property.<p>
     *
     * @returns a collection of values for the SampleDate property.
     */
    Date getSampleDate();


    /**
     * Adds a SampleDate property value.<p>
     *
     * @param newSampleDate the SampleDate property value to be added
     */
    void setSampleDate(Date newSampleDate);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000070
     */

    /**
     * Gets all property values for the LabResultNumberOfSamples property.<p>
     *
     * @returns a collection of values for the LabResultNumberOfSamples property.
     */
    Integer getLabResultNumberOfSamples();


    /**
     * Adds a LabResultNumberOfSamples property value.<p>
     *
     * @param newLabResultNumberOfSamples the LabResultNumberOfSamples property value to be added
     */
    void setLabResultNumberOfSamples(Integer newLabResultNumberOfSamples);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000125
     */

    /**
     * Gets all property values for the LaboratoryResultValue property.<p>
     *
     * @returns a collection of values for the LaboratoryResultValue property.
     */
    String getLaboratoryResultValue();


    /**
     * Adds a LaboratoryResultValue property value.<p>
     *
     * @param newLaboratoryResultValue the LaboratoryResultValue property value to be added
     */
    void setLaboratoryResultValue(String newLaboratoryResultValue);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000163
     */

    /**
     * Gets all property values for the LabResultSequenceNumber property.<p>
     *
     * @returns a collection of values for the LabResultSequenceNumber property.
     */
    Integer getLabResultSequenceNumber();


    /**
     * Adds a LabResultSequenceNumber property value.<p>
     *
     * @param newLabResultSequenceNumber the LabResultSequenceNumber property value to be added
     */
    void setLabResultSequenceNumber(Integer newLabResultSequenceNumber);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000317
     */

    /**
     * Gets all property values for the Range property.<p>
     *
     * @returns a collection of values for the Range property.
     */
    String getRange();


    /**
     * Adds a Range property value.<p>
     *
     * @param newRange the Range property value to be added
     */
    void setRange(String newRange);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000402
     */

    /**
     * Gets all property values for the LabResultUnit property.<p>
     *
     * @returns a collection of values for the LabResultUnit property.
     */
    String getLabResultUnit();


    /**
     * Adds a LabResultUnit property value.<p>
     *
     * @param newLabResultUnit the LabResultUnit property value to be added
     */
    void setLabResultUnit(String newLabResultUnit);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000467
     */

    /**
     * Gets all property values for the LabNote property.<p>
     *
     * @returns a collection of values for the LabNote property.
     */
    String getLabNote();


    /**
     * Adds a LabNote property value.<p>
     *
     * @param newLabNote the LabNote property value to be added
     */
    void setLabNote(String newLabNote);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000487
     */

    /**
     * Gets all property values for the LabResultNameValue property.<p>
     *
     * @returns a collection of values for the LabResultNameValue property.
     */
    String getLabResultNameValue();


    /**
     * Adds a LabResultNameValue property value.<p>
     *
     * @param newLabResultNameValue the LabResultNameValue property value to be added
     */
    void setLabResultNameValue(String newLabResultNameValue);


}
