package com.apixio.model.owl.interfaces;

/**
 OWL annotation driven imports 
**/
import com.apixio.model.owl.interfaces.donotimplement.ClinicalRoleType;
import com.apixio.model.owl.interfaces.donotimplement.Human;


/**
 * 
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: MedicalProfessional <br>
 * @version generated on Fri Mar 11 09:53:02 PST 2016 by jctoledo
 */

public interface MedicalProfessional  extends Human {


    void setOrganization(Organization o);

    Organization getOrganization();
    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000084
     */

    /**
     * Gets all property values for the ClinicalRole property.<p>
     *
     * @returns a collection of values for the ClinicalRole property.
     */
    ClinicalRoleType getClinicalRole();


    /**
     * Adds a ClinicalRole property value.<p>
     *
     * @param newClinicalRole the ClinicalRole property value to be added
     */
    void setClinicalRole(ClinicalRoleType newClinicalRole);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000155
     */

    /**
     * Gets all property values for the NationalProviderIdentifier property.<p>
     *
     * @returns a collection of values for the NationalProviderIdentifier property.
     */
    ExternalIdentifier getNationalProviderIdentifier();


    /**
     * Adds a NationalProviderIdentifier property value.<p>
     *
     * @param newNationalProviderIdentifier the NationalProviderIdentifier property value to be added
     */
    void setNationalProviderIdentifier(ExternalIdentifier newNationalProviderIdentifier);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000136
     */

    /**
     * Gets all property values for the Title property.<p>
     *
     * @returns a collection of values for the Title property.
     */
    String getTitle();


    /**
     * Adds a Title property value.<p>
     *
     * @param newTitle the Title property value to be added
     */
    void setTitle(String newTitle);



}
