package com.apixio.model.owl.interfaces;

import com.apixio.XUUID;
import com.apixio.model.owl.interfaces.donotimplement.Label;
import com.apixio.model.owl.interfaces.donotimplement.NameType;

import java.util.Collection;

/**
 * OWL annotation driven imports
 **/


/**
 * 
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: Name <br>
 * @version generated on Fri Mar 11 09:53:01 PST 2016 by jctoledo
 */

public interface Name  extends Label {



    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000637
     */

    /**
     * Gets all property values for the NameType property.<p>
     *
     * @returns a collection of values for the NameType property.
     */
    NameType getNameType();


    /**
     * Adds a NameType property value.<p>
     *
     * @param newNameType the NameType property value to be added
     */
    void setNameType(NameType newNameType);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000005
     */

    /**
     * Gets all property values for the FamilyNames property.<p>
     *
     * @returns a collection of values for the FamilyNames property.
     * Collection<? extends String> getFamilyNames();
     */
    Collection<String> getFamilyNames();

    /**
     * Add an element to the list
     */
    Collection<String> addFamilyNames(String anItem);

    /**
     * get element from list by Id
     */
    String getFamilyNamesById(XUUID anID);

    /**
     * Adds a FamilyNames property value.<p>
     *
     * @param newFamilyNames the FamilyNames property value to be added
     * void setFamilyNames(Collection<? extends String> newFamilyNames);
     */
    void setFamilyNames(Collection<String> newFamilyNames);
    /* ***************************************************
     * Property http://apixio.com/ontology/alo#009834
     */

    /**
     * Gets all property values for the SuffixNames property.<p>
     *
     * @returns a collection of values for the SuffixNames property.
     * Collection<? extends String> getSuffixNames();
     */
    Collection<String> getSuffixNames();

    /**
     * Add an element to the list
     */
    Collection<String> addSuffixNames(String anItem);

    /**
     * get element from list by Id
     */
    String getSuffixNamesById(XUUID anID);

    /**
     * Adds a SuffixNames property value.<p>
     *
     * @param newSuffixNames the SuffixNames property value to be added
     * void setSuffixNames(Collection<? extends String> newSuffixNames);
     */
    void setSuffixNames(Collection<String> newSuffixNames);
    /* ***************************************************
     * Property http://apixio.com/ontology/alo#012321
     */

    /**
     * Gets all property values for the PrefixNames property.<p>
     *
     * @returns a collection of values for the PrefixNames property.
     * Collection<? extends String> getPrefixNames();
     */
    Collection<String> getPrefixNames();

    /**
     * Add an element to the list
     */
    Collection<String> addPrefixNames(String anItem);

    /**
     * get element from list by Id
     */
    String getPrefixNamesById(XUUID anID);

    /**
     * Adds a PrefixNames property value.<p>
     *
     * @param newPrefixNames the PrefixNames property value to be added
     * void setPrefixNames(Collection<? extends String> newPrefixNames);
     */
    void setPrefixNames(Collection<String> newPrefixNames);
    /* ***************************************************
     * Property http://apixio.com/ontology/alo#888880
     */

    /**
     * Gets all property values for the GivenNames property.<p>
     *
     * @returns a collection of values for the GivenNames property.
     * Collection<? extends String> getGivenNames();
     */
    Collection<String> getGivenNames();

    /**
     * Add an element to the list
     */
    Collection<String> addGivenNames(String anItem);

    /**
     * get element from list by Id
     */
    String getGivenNamesById(XUUID anID);

    /**
     * Adds a GivenNames property value.<p>
     *
     * @param newGivenNames the GivenNames property value to be added
     * void setGivenNames(Collection<? extends String> newGivenNames);
     */
    void setGivenNames(Collection<String> newGivenNames);


}
