package com.apixio.model.owl.interfaces;

import java.util.Collection;

/**
 OWL annotation driven imports 
**/
import com.apixio.model.owl.interfaces.donotimplement.Collective;
import com.apixio.model.owl.interfaces.donotimplement.ProvenancedEntity;


/**
 * 
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: Organization <br>
 * @version generated on Fri Mar 11 09:53:01 PST 2016 by jctoledo
 */

public interface Organization  extends Collective, ProvenancedEntity {



    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000155
     */

    /**
     * Gets all property values for the NationalProviderIdentifier property.<p>
     *
     * @returns a collection of values for the NationalProviderIdentifier property.
     */
    ExternalIdentifier getNationalProviderIdentifier();


    /**
     * Adds a NationalProviderIdentifier property value.<p>
     *
     * @param newNationalProviderIdentifier the NationalProviderIdentifier property value to be added
     */
    void setNationalProviderIdentifier(ExternalIdentifier newNationalProviderIdentifier);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000424
     */

    /**
     * Gets all property values for the ContactDetails property.<p>
     *
     * @returns a collection of values for the ContactDetails property.
     */
    ContactDetails getContactDetails();


    /**
     * Adds a ContactDetails property value.<p>
     *
     * @param newContactDetails the ContactDetails property value to be added
     */
    void setContactDetails(ContactDetails newContactDetails);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000498
     */

    /**
     * Gets all property values for the OrganizationNameValue property.<p>
     *
     * @returns a collection of values for the OrganizationNameValue property.
     */
    String getOrganizationNameValue();


    /**
     * Adds a OrganizationNameValue property value.<p>
     *
     * @param newOrganizationNameValue the OrganizationNameValue property value to be added
     */
    void setOrganizationNameValue(String newOrganizationNameValue);



}

