package com.apixio.model.owl.interfaces;

import java.util.Collection;

/**
 OWL annotation driven imports 
**/
import com.apixio.XUUID;
import com.apixio.model.owl.interfaces.donotimplement.ProvenancedEntity;
import com.apixio.model.owl.interfaces.donotimplement.TextualEntity;

import java.net.URI;


/**
 * 
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: Page <br>
 * @version generated on Fri Mar 11 09:53:01 PST 2016 by jctoledo
 */

public interface Page  extends TextualEntity,ProvenancedEntity {



    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000118
     */

    /**
     * Gets all property values for the TextRenderings property.<p>
     *
     * @returns a collection of values for the TextRenderings property.
     * Collection<? extends TextRendering> getTextRenderings();
     */
    Collection<TextRendering> getTextRenderings();

    /**
     * Add an element to the list
     */
    Collection<TextRendering> addTextRenderings(TextRendering anItem);

    /**
     * get element from list by Id
     */
    TextRendering getTextRenderingsById(XUUID anID);

    /**
     * Adds a TextRenderings property value.<p>
     *
     * @param newTextRenderings the TextRenderings property value to be added
     * void setTextRenderings(Collection<? extends TextRendering> newTextRenderings);
     */
    void setTextRenderings(Collection<TextRendering> newTextRenderings);
    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000123
     */

    /**
     * Gets all property values for the ImageRenderings property.<p>
     *
     * @returns a collection of values for the ImageRenderings property.
     * Collection<? extends ImageRendering> getImageRenderings();
     */
    Collection<ImageRendering> getImageRenderings();

    /**
     * Add an element to the list
     */
    Collection<ImageRendering> addImageRenderings(ImageRendering anItem);

    /**
     * get element from list by Id
     */
    ImageRendering getImageRenderingsById(XUUID anID);

    /**
     * Adds a ImageRenderings property value.<p>
     *
     * @param newImageRenderings the ImageRenderings property value to be added
     * void setImageRenderings(Collection<? extends ImageRendering> newImageRenderings);
     */
    void setImageRenderings(Collection<ImageRendering> newImageRenderings);
    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000096
     */

    /**
     * Gets all property values for the PageNumber property.<p>
     *
     * @returns a collection of values for the PageNumber property.
     */
    Integer getPageNumber();


    /**
     * Adds a PageNumber property value.<p>
     *
     * @param newPageNumber the PageNumber property value to be added
     */
    void setPageNumber(Integer newPageNumber);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000149
     */

    /**
     * Gets all property values for the PageClassifications property.<p>
     *
     * @returns a collection of values for the PageClassifications property.
     * Collection<? extends String> getPageClassifications();
     */
    Collection<String> getPageClassifications();

    /**
     * Add an element to the list
     */
    Collection<String> addPageClassifications(String anItem);

    /**
     * get element from list by Id
     */
    String getPageClassificationsById(XUUID anID);

    /**
     * Adds a PageClassifications property value.<p>
     *
     * @param newPageClassifications the PageClassifications property value to be added
     * void setPageClassifications(Collection<? extends String> newPageClassifications);
     */
    void setPageClassifications(Collection<String> newPageClassifications);

}
