package com.apixio.model.owl.interfaces;

import com.apixio.XUUID;
import com.apixio.model.owl.interfaces.donotimplement.Human;

import java.util.Collection;

/**
 * OWL annotation driven imports
 **/


/**
 * <p/>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: Patient <br>
 *
 * @version generated on Fri Mar 11 09:53:00 PST 2016 by jctoledo
 */

public interface Patient extends Human {

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000032
     */

    /**
     * Gets all property values for the MedicalProcedures property.<p>
     *
     * @returns a collection of values for the MedicalProcedures property.
     * Collection<? extends Procedure> getMedicalProcedures();
     */
    Collection<Procedure> getMedicalProcedures();

    /**
     * Add an element to the list
     */
    Collection<Procedure> addMedicalProcedures(Procedure anItem);

    /**
     * get element from list by Id
     */
    Procedure getMedicalProceduresById(XUUID anID);

    /**
     * Adds a MedicalProcedures property value.<p>
     *
     * @param newMedicalProcedures the MedicalProcedures property value to be added
     * void setMedicalProcedures(Collection<? extends Procedure> newMedicalProcedures);
     */
    void setMedicalProcedures(Collection<Procedure> newMedicalProcedures);
    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000073
     */

    /**
     * Gets all property values for the FamilyHistories property.<p>
     *
     * @returns a collection of values for the FamilyHistories property.
     * Collection<? extends FamilyHistory> getFamilyHistories();
     */
    Collection<FamilyHistory> getFamilyHistories();

    /**
     * Add an element to the list
     */
    Collection<FamilyHistory> addFamilyHistories(FamilyHistory anItem);

    /**
     * get element from list by Id
     */
    FamilyHistory getFamilyHistoriesById(XUUID anID);

    /**
     * Adds a FamilyHistories property value.<p>
     *
     * @param newFamilyHistories the FamilyHistories property value to be added
     * void setFamilyHistories(Collection<? extends FamilyHistory> newFamilyHistories);
     */
    void setFamilyHistories(Collection<FamilyHistory> newFamilyHistories);
    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000076
     */

    /**
     * Gets all property values for the SocialHistories property.<p>
     *
     * @returns a collection of values for the SocialHistories property.
     * Collection<? extends SocialHistory> getSocialHistories();
     */
    Collection<SocialHistory> getSocialHistories();

    /**
     * Add an element to the list
     */
    Collection<SocialHistory> addSocialHistories(SocialHistory anItem);

    /**
     * get element from list by Id
     */
    SocialHistory getSocialHistoriesById(XUUID anID);

    /**
     * Adds a SocialHistories property value.<p>
     *
     * @param newSocialHistories the SocialHistories property value to be added
     * void setSocialHistories(Collection<? extends SocialHistory> newSocialHistories);
     */
    void setSocialHistories(Collection<SocialHistory> newSocialHistories);
    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000078
     */

    /**
     * Gets all property values for the PatientCareSites property.<p>
     *
     * @returns a collection of values for the PatientCareSites property.
     * Collection<? extends CareSite> getPatientCareSites();
     */
    Collection<CareSite> getPatientCareSites();

    /**
     * Add an element to the list
     */
    Collection<CareSite> addPatientCareSites(CareSite anItem);

    /**
     * get element from list by Id
     */
    CareSite getPatientCareSitesById(XUUID anID);

    /**
     * Adds a PatientCareSites property value.<p>
     *
     * @param newPatientCareSites the PatientCareSites property value to be added
     * void setPatientCareSites(Collection<? extends CareSite> newPatientCareSites);
     */
    void setPatientCareSites(Collection<CareSite> newPatientCareSites);
    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000086
     */

    /**
     * Gets all property values for the MedicalProfessionals property.<p>
     *
     * @returns a collection of values for the MedicalProfessionals property.
     * Collection<? extends MedicalProfessional> getMedicalProfessionals();
     */
    Collection<MedicalProfessional> getMedicalProfessionals();

    /**
     * Add an element to the list
     */
    Collection<MedicalProfessional> addMedicalProfessionals(MedicalProfessional anItem);

    /**
     * get element from list by Id
     */
    MedicalProfessional getMedicalProfessionalsById(XUUID anID);

    /**
     * Adds a MedicalProfessionals property value.<p>
     *
     * @param newMedicalProfessionals the MedicalProfessionals property value to be added
     * void setMedicalProfessionals(Collection<? extends MedicalProfessional> newMedicalProfessionals);
     */
    void setMedicalProfessionals(Collection<MedicalProfessional> newMedicalProfessionals);
    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000141
     */

    /**
     * Gets all property values for the RiskAdjustmentClaims property.<p>
     *
     * @returns a collection of values for the RiskAdjustmentClaims property.
     * Collection<? extends RiskAdjustmentInsuranceClaim> getRiskAdjustmentClaims();
     */
    Collection<RiskAdjustmentInsuranceClaim> getRiskAdjustmentClaims();

    /**
     * Add an element to the list
     */
    Collection<RiskAdjustmentInsuranceClaim> addRiskAdjustmentClaims(RiskAdjustmentInsuranceClaim anItem);

    /**
     * get element from list by Id
     */
    RiskAdjustmentInsuranceClaim getRiskAdjustmentClaimsById(XUUID anID);

    /**
     * Adds a RiskAdjustmentClaims property value.<p>
     *
     * @param newRiskAdjustmentClaims the RiskAdjustmentClaims property value to be added
     * void setRiskAdjustmentClaims(Collection<? extends RiskAdjustmentInsuranceClaim> newRiskAdjustmentClaims);
     */
    void setRiskAdjustmentClaims(Collection<RiskAdjustmentInsuranceClaim> newRiskAdjustmentClaims);
    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000144
     */

    /**
     * Gets all property values for the Encounters property.<p>
     *
     * @returns a collection of values for the Encounters property.
     * Collection<? extends PatientEncounter> getEncounters();
     */
    Collection<PatientEncounter> getEncounters();

    /**
     * Add an element to the list
     */
    Collection<PatientEncounter> addEncounters(PatientEncounter anItem);

    /**
     * get element from list by Id
     */
    PatientEncounter getEncountersById(XUUID anID);

    /**
     * Adds a Encounters property value.<p>
     *
     * @param newEncounters the Encounters property value to be added
     * void setEncounters(Collection<? extends PatientEncounter> newEncounters);
     */
    void setEncounters(Collection<PatientEncounter> newEncounters);
    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000150
     */

    /**
     * Gets all property values for the FeeForServiceClaims property.<p>
     *
     * @returns a collection of values for the FeeForServiceClaims property.
     * Collection<? extends FeeForServiceInsuranceClaim> getFeeForServiceClaims();
     */
    Collection<FeeForServiceInsuranceClaim> getFeeForServiceClaims();

    /**
     * Add an element to the list
     */
    Collection<FeeForServiceInsuranceClaim> addFeeForServiceClaims(FeeForServiceInsuranceClaim anItem);

    /**
     * get element from list by Id
     */
    FeeForServiceInsuranceClaim getFeeForServiceClaimsById(XUUID anID);

    /**
     * Adds a FeeForServiceClaims property value.<p>
     *
     * @param newFeeForServiceClaims the FeeForServiceClaims property value to be added
     * void setFeeForServiceClaims(Collection<? extends FeeForServiceInsuranceClaim> newFeeForServiceClaims);
     */
    void setFeeForServiceClaims(Collection<FeeForServiceInsuranceClaim> newFeeForServiceClaims);
    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000231
     */

    /**
     * Gets all property values for the Documents property.<p>
     *
     * @returns a collection of values for the Documents property.
     * Collection<? extends Document> getDocuments();
     */
    Collection<Document> getDocuments();

    /**
     * Add an element to the list
     */
    Collection<Document> addDocuments(Document anItem);

    /**
     * get element from list by Id
     */
    Document getDocumentsById(XUUID anID);

    /**
     * Adds a Documents property value.<p>
     *
     * @param newDocuments the Documents property value to be added
     * void setDocuments(Collection<? extends Document> newDocuments);
     */
    void setDocuments(Collection<Document> newDocuments);
    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000428
     */

    /**
     * Gets all property values for the AlternateDemographicss property.<p>
     *
     * @returns a collection of values for the AlternateDemographicss property.
     * Collection<? extends Demographics> getAlternateDemographicss();
     */
    Collection<Demographics> getAlternateDemographicss();

    /**
     * Add an element to the list
     */
    Collection<Demographics> addAlternateDemographicss(Demographics anItem);

    /**
     * get element from list by Id
     */
    Demographics getAlternateDemographicssById(XUUID anID);

    /**
     * Adds a AlternateDemographicss property value.<p>
     *
     * @param newAlternateDemographicss the AlternateDemographicss property value to be added
     * void setAlternateDemographicss(Collection<? extends Demographics> newAlternateDemographicss);
     */
    void setAlternateDemographicss(Collection<Demographics> newAlternateDemographicss);
    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000432
     */

    /**
     * Gets all property values for the PrimaryCareProviders property.<p>
     *
     * @returns a collection of values for the PrimaryCareProviders property.
     * Collection<? extends PrimaryCareProvider> getPrimaryCareProviders();
     */
    Collection<PrimaryCareProvider> getPrimaryCareProviders();

    /**
     * Add an element to the list
     */
    Collection<PrimaryCareProvider> addPrimaryCareProviders(PrimaryCareProvider anItem);

    /**
     * get element from list by Id
     */
    PrimaryCareProvider getPrimaryCareProvidersById(XUUID anID);

    /**
     * Adds a PrimaryCareProviders property value.<p>
     *
     * @param newPrimaryCareProviders the PrimaryCareProviders property value to be added
     * void setPrimaryCareProviders(Collection<? extends PrimaryCareProvider> newPrimaryCareProviders);
     */
    void setPrimaryCareProviders(Collection<PrimaryCareProvider> newPrimaryCareProviders);
    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000457
     */

    /**
     * Gets all property values for the InsurancePolicies property.<p>
     *
     * @returns a collection of values for the InsurancePolicies property.
     * Collection<? extends InsurancePolicy> getInsurancePolicies();
     */
    Collection<InsurancePolicy> getInsurancePolicies();

    /**
     * Add an element to the list
     */
    Collection<InsurancePolicy> addInsurancePolicies(InsurancePolicy anItem);

    /**
     * get element from list by Id
     */
    InsurancePolicy getInsurancePoliciesById(XUUID anID);

    /**
     * Adds a InsurancePolicies property value.<p>
     *
     * @param newInsurancePolicies the InsurancePolicies property value to be added
     * void setInsurancePolicies(Collection<? extends InsurancePolicy> newInsurancePolicies);
     */
    void setInsurancePolicies(Collection<InsurancePolicy> newInsurancePolicies);
    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000472
     */

    /**
     * Gets all property values for the Problems property.<p>
     *
     * @returns a collection of values for the Problems property.
     * Collection<? extends Problem> getProblems();
     */
    Collection<Problem> getProblems();

    /**
     * Add an element to the list
     */
    Collection<Problem> addProblems(Problem anItem);

    /**
     * get element from list by Id
     */
    Problem getProblemsById(XUUID anID);

    /**
     * Adds a Problems property value.<p>
     *
     * @param newProblems the Problems property value to be added
     * void setProblems(Collection<? extends Problem> newProblems);
     */
    void setProblems(Collection<Problem> newProblems);
    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000473
     */

    /**
     * Gets all property values for the Prescriptions property.<p>
     *
     * @returns a collection of values for the Prescriptions property.
     * Collection<? extends Prescription> getPrescriptions();
     */
    Collection<Prescription> getPrescriptions();

    /**
     * Add an element to the list
     */
    Collection<Prescription> addPrescriptions(Prescription anItem);

    /**
     * get element from list by Id
     */
    Prescription getPrescriptionsById(XUUID anID);

    /**
     * Adds a Prescriptions property value.<p>
     *
     * @param newPrescriptions the Prescriptions property value to be added
     * void setPrescriptions(Collection<? extends Prescription> newPrescriptions);
     */
    void setPrescriptions(Collection<Prescription> newPrescriptions);
    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000476
     */

    /**
     * Gets all property values for the BiometricValues property.<p>
     *
     * @returns a collection of values for the BiometricValues property.
     * Collection<? extends BiometricValue> getBiometricValues();
     */
    Collection<BiometricValue> getBiometricValues();

    /**
     * Add an element to the list
     */
    Collection<BiometricValue> addBiometricValues(BiometricValue anItem);

    /**
     * get element from list by Id
     */
    BiometricValue getBiometricValuesById(XUUID anID);

    /**
     * Adds a BiometricValues property value.<p>
     *
     * @param newBiometricValues the BiometricValues property value to be added
     * void setBiometricValues(Collection<? extends BiometricValue> newBiometricValues);
     */
    void setBiometricValues(Collection<BiometricValue> newBiometricValues);
    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000479
     */

    /**
     * Gets all property values for the Allergies property.<p>
     *
     * @returns a collection of values for the Allergies property.
     * Collection<? extends Allergy> getAllergies();
     */
    Collection<Allergy> getAllergies();

    /**
     * Add an element to the list
     */
    Collection<Allergy> addAllergies(Allergy anItem);

    /**
     * get element from list by Id
     */
    Allergy getAllergiesById(XUUID anID);

    /**
     * Adds a Allergies property value.<p>
     *
     * @param newAllergies the Allergies property value to be added
     * void setAllergies(Collection<? extends Allergy> newAllergies);
     */
    void setAllergies(Collection<Allergy> newAllergies);
    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000486
     */

    /**
     * Gets all property values for the LabResults property.<p>
     *
     * @returns a collection of values for the LabResults property.
     * Collection<? extends LabResult> getLabResults();
     */
    Collection<LabResult> getLabResults();

    /**
     * Add an element to the list
     */
    Collection<LabResult> addLabResults(LabResult anItem);

    /**
     * get element from list by Id
     */
    LabResult getLabResultsById(XUUID anID);

    /**
     * Adds a LabResults property value.<p>
     *
     * @param newLabResults the LabResults property value to be added
     * void setLabResults(Collection<? extends LabResult> newLabResults);
     */
    void setLabResults(Collection<LabResult> newLabResults);
    /* ***************************************************
     * Property http://apixio.com/ontology/alo#610006
     */

    /**
     * Gets all property values for the Immunizations property.<p>
     *
     * @returns a collection of values for the Immunizations property.
     * Collection<? extends Immunization> getImmunizations();
     */
    Collection<Immunization> getImmunizations();

    /**
     * Add an element to the list
     */
    Collection<Immunization> addImmunizations(Immunization anItem);

    /**
     * get element from list by Id
     */
    Immunization getImmunizationsById(XUUID anID);

    /**
     * Adds a Immunizations property value.<p>
     *
     * @param newImmunizations the Immunizations property value to be added
     * void setImmunizations(Collection<? extends Immunization> newImmunizations);
     */
    void setImmunizations(Collection<Immunization> newImmunizations);


}
