package com.apixio.model.owl.interfaces;

/**
 OWL annotation driven imports 
**/

import com.apixio.XUUID;
import com.apixio.model.owl.interfaces.donotimplement.InsuranceClaimableEvent;

import java.util.Collection;


/**
 * 
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: Prescription <br>
 * @version generated on Fri Mar 11 09:53:02 PST 2016 by jctoledo
 */

public interface Prescription  extends  InsuranceClaimableEvent {



    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000434
     */

    /**
     * Gets all property values for the PrescribedDrugs property.<p>
     *
     * @returns a collection of values for the PrescribedDrugs property.
     * Collection<? extends Medication> getPrescribedDrugs();
     */
    Collection<Medication> getPrescribedDrugs();

    /**
     * Add an element to the list
     */
    Collection<Medication> addPrescribedDrugs(Medication anItem);

    /**
     * get element from list by Id
     */
    Medication getPrescribedDrugsById(XUUID anID);

    /**
     * Adds a PrescribedDrugs property value.<p>
     *
     * @param newPrescribedDrugs the PrescribedDrugs property value to be added
     * void setPrescribedDrugs(Collection<? extends Medication> newPrescribedDrugs);
     */
    void setPrescribedDrugs(Collection<Medication> newPrescribedDrugs);
    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000439
     */

    /**
     * Gets all property values for the PrescriptionFillDate property.<p>
     *
     * @returns a collection of values for the PrescriptionFillDate property.
     */
    Date getPrescriptionFillDate();


    /**
     * Adds a PrescriptionFillDate property value.<p>
     *
     * @param newPrescriptionFillDate the PrescriptionFillDate property value to be added
     */
    void setPrescriptionFillDate(Date newPrescriptionFillDate);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000440
     */

    /**
     * Gets all property values for the PrescriptionEndDate property.<p>
     *
     * @returns a collection of values for the PrescriptionEndDate property.
     */
    Date getPrescriptionEndDate();


    /**
     * Adds a PrescriptionEndDate property value.<p>
     *
     * @param newPrescriptionEndDate the PrescriptionEndDate property value to be added
     */
    void setPrescriptionEndDate(Date newPrescriptionEndDate);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000441
     */

    /**
     * Gets all property values for the PrescriptionDate property.<p>
     *
     * @returns a collection of values for the PrescriptionDate property.
     */
    Date getPrescriptionDate();


    /**
     * Adds a PrescriptionDate property value.<p>
     *
     * @param newPrescriptionDate the PrescriptionDate property value to be added
     */
    void setPrescriptionDate(Date newPrescriptionDate);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000427
     */

    /**
     * Gets all property values for the NumberOfRefillsRemaining property.<p>
     *
     * @returns a collection of values for the NumberOfRefillsRemaining property.
     */
    Integer getNumberOfRefillsRemaining();


    /**
     * Adds a NumberOfRefillsRemaining property value.<p>
     *
     * @param newNumberOfRefillsRemaining the NumberOfRefillsRemaining property value to be added
     */
    void setNumberOfRefillsRemaining(Integer newNumberOfRefillsRemaining);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000433
     */

    /**
     * Gets all property values for the IsActivePrescription property.<p>
     *
     * @returns a collection of values for the IsActivePrescription property.
     */
    Boolean getIsActivePrescription();


    /**
     * Adds a IsActivePrescription property value.<p>
     *
     * @param newIsActivePrescription the IsActivePrescription property value to be added
     */
    void setIsActivePrescription(Boolean newIsActivePrescription);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000438
     */

    /**
     * Gets all property values for the Sig property.<p>
     *
     * @returns a collection of values for the Sig property.
     */
    String getSig();


    /**
     * Adds a Sig property value.<p>
     *
     * @param newSig the Sig property value to be added
     */
    void setSig(String newSig);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000442
     */

    /**
     * Gets all property values for the PrescriptionQuantity property.<p>
     *
     * @returns a collection of values for the PrescriptionQuantity property.
     */
    Double getPrescriptionQuantity();


    /**
     * Adds a PrescriptionQuantity property value.<p>
     *
     * @param newPrescriptionQuantity the PrescriptionQuantity property value to be added
     */
    void setPrescriptionQuantity(Double newPrescriptionQuantity);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000443
     */

    /**
     * Gets all property values for the PrescriptionFrequency property.<p>
     *
     * @returns a collection of values for the PrescriptionFrequency property.
     */
    String getPrescriptionFrequency();


    /**
     * Adds a PrescriptionFrequency property value.<p>
     *
     * @param newPrescriptionFrequency the PrescriptionFrequency property value to be added
     */
    void setPrescriptionFrequency(String newPrescriptionFrequency);



}
