package com.apixio.model.owl.interfaces;

/**
 OWL annotation driven imports 
**/


/**
 * 
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: PrimaryCareProvider <br>
 * @version generated on Fri Mar 11 09:53:02 PST 2016 by jctoledo
 */

public interface PrimaryCareProvider  extends com.apixio.model.owl.interfaces.MedicalProfessional {



    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000142
     */

    /**
     * Gets all property values for the DateRangeForCareOfPatient property.<p>
     *
     * @returns a collection of values for the DateRangeForCareOfPatient property.
     */
    DateRange getDateRangeForCareOfPatient();


    /**
     * Adds a DateRangeForCareOfPatient property value.<p>
     *
     * @param newDateRangeForCareOfPatient the DateRangeForCareOfPatient property value to be added
     */
    void setDateRangeForCareOfPatient(DateRange newDateRangeForCareOfPatient);




}
