package com.apixio.model.owl.interfaces;

import com.apixio.XUUID;
import com.apixio.model.owl.interfaces.donotimplement.InsuranceClaimableEvent;
import com.apixio.model.owl.interfaces.donotimplement.MedicalEvent;

import java.util.Collection;

/**
 * OWL annotation driven imports
 **/


/**
 * 
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: Procedure <br>
 * @version generated on Thu Mar 31 16:06:26 PDT 2016 by jctoledo
 */

public interface Procedure  extends MedicalEvent, InsuranceClaimableEvent {



    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000029
     */

    /**
     * Gets all property values for the BodySite property.<p>
     *
     * @returns a collection of values for the BodySite property.
     */
    AnatomicalEntity getBodySite();


    /**
     * Adds a BodySite property value.<p>
     *
     * @param newBodySite the BodySite property value to be added
     */
    void setBodySite(AnatomicalEntity newBodySite);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000030
     */

    /**
     * Gets all property values for the DiagnosisCodes property.<p>
     *
     * @returns a collection of values for the DiagnosisCodes property.
     * Collection<? extends ClinicalCode> getDiagnosisCodes();
     * ICD codes associated with a RAPS diagnosis cluster
     *
     */
    Collection<ClinicalCode> getDiagnosisCodes();

    /**
     * Add an element to the list
     * ICD codes associated with a RAPS diagnosis cluster
     *
     */
    Collection<ClinicalCode> addDiagnosisCodes(ClinicalCode anItem);

    /**
     * get element from list by Id
     * ICD codes associated with a RAPS diagnosis cluster
     *
     */
    ClinicalCode getDiagnosisCodesById(XUUID anID);

    /**
     * Adds a DiagnosisCodes property value.<p>
     *
     * @param newDiagnosisCodes the DiagnosisCodes property value to be added
     * void setDiagnosisCodes(Collection<? extends ClinicalCode> newDiagnosisCodes);
     * ICD codes associated with a RAPS diagnosis cluster
     *
     */
    void setDiagnosisCodes(Collection<ClinicalCode> newDiagnosisCodes);
    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000502
     */

    /**
     * Gets all property values for the MedicalProcedureDateRange property.<p>
     *
     * @returns a collection of values for the MedicalProcedureDateRange property.
     */
    DateRange getMedicalProcedureDateRange();


    /**
     * Adds a MedicalProcedureDateRange property value.<p>
     *
     * @param newMedicalProcedureDateRange the MedicalProcedureDateRange property value to be added
     */
    void setMedicalProcedureDateRange(DateRange newMedicalProcedureDateRange);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000031
     */

    /**
     * Gets all property values for the MedicalProcedureInterpretation property.<p>
     *
     * @returns a collection of values for the MedicalProcedureInterpretation property.
     */
    String getMedicalProcedureInterpretation();


    /**
     * Adds a MedicalProcedureInterpretation property value.<p>
     *
     * @param newMedicalProcedureInterpretation the MedicalProcedureInterpretation property value to be added
     */
    void setMedicalProcedureInterpretation(String newMedicalProcedureInterpretation);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000501
     */

    /**
     * Gets all property values for the MedicalProcedureNameValue property.<p>
     *
     * @returns a collection of values for the MedicalProcedureNameValue property.
     */
    String getMedicalProcedureNameValue();


    /**
     * Adds a MedicalProcedureNameValue property value.<p>
     *
     * @param newMedicalProcedureNameValue the MedicalProcedureNameValue property value to be added
     */
    void setMedicalProcedureNameValue(String newMedicalProcedureNameValue);



}
