package com.apixio.model.owl.interfaces;

/**
 * OWL annotation driven imports
 **/


/**
 * 
 * A validation error found on an RA claim submitted to CMS by a payor or provider - https://www.cms.gov/Research-Statistics-Data-and-Systems/CMS-Information-Technology/mapdhelpdesk/Downloads/Announcement-of-the-November-2014-Software-Release.pdf
	*
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: RAPSValidationError <br>
 * @version generated on Wed Jun 08 11:20:18 PDT 2016 by jctoledo
 */

public interface RAPSValidationError  extends CMSValidationError {





}
