package com.apixio.model.owl.interfaces;

/**
 * OWL annotation driven imports
 **/

import com.apixio.model.owl.interfaces.donotimplement.InformationContentQuality;
import com.apixio.model.owl.interfaces.donotimplement.RiskAdjustmentInsuranceClaimTypeValue;

/**
 * RiskAdjustmentInsuranceClaimTypeValue
 * 
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: RiskAdjustmentInsuranceClaimType <br>
 * @version generated on Tue Sep 13 11:58:48 PDT 2016 by jctoledo
 */

public interface RiskAdjustmentInsuranceClaimType extends InformationContentQuality {

RiskAdjustmentInsuranceClaimTypeValue getRiskAdjustmentInsuranceClaimTypeValue();

void setRiskAdjustmentInsuranceClaimTypeValue(RiskAdjustmentInsuranceClaimTypeValue en);




}