package com.apixio.model.owl.interfaces;

/**
 OWL annotation driven imports 
**/


import com.apixio.XUUID;

import java.net.URI;
import java.util.Collection;

/**
 * 
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: RiskAdjustmentInsuranceClaim <br>
 * @version generated on Fri Mar 11 09:53:02 PST 2016 by jctoledo
 */

public interface RiskAdjustmentInsuranceClaim  extends InsuranceClaim {

/**
 * OWL annotation driven methods
 **/
    /**
     * source encounter
     */
    XUUID getSourceEncounterId();
    void setSourceEncounterId(XUUID anID);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000162
     */

    /**
     * Gets all property values for the DateOfServiceRange property.<p>
     *
     *
     * @returns a collection of values for the DateOfServiceRange property.
     */
    DateRange getDateOfServiceRange();


    /**
     * Adds a DateOfServiceRange property value.<p>
     *
     *
     * @param newDateOfServiceRange the DateOfServiceRange property value to be added
     */
    void setDateOfServiceRange(DateRange newDateOfServiceRange);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000202
     */

    /**
     * Gets all property values for the PatientEncounterSwitchType property.<p>
     *
     *
     * @returns a collection of values for the PatientEncounterSwitchType property.
     */
    PatientEncounterSwitchType getPatientEncounterSwitchType();


    /**
     * Adds a PatientEncounterSwitchType property value.<p>
     *
     *
     * @param newPatientEncounterSwitchType the PatientEncounterSwitchType property value to be added
     */
    void setPatientEncounterSwitchType(PatientEncounterSwitchType newPatientEncounterSwitchType);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000211
     */

    /**
     * Gets all property values for the RiskAdjustmentInsuranceClaimType property.<p>
     *
     *
     * @returns a collection of values for the RiskAdjustmentInsuranceClaimType property.
     */
    RiskAdjustmentInsuranceClaimType getRiskAdjustmentInsuranceClaimType();


    /**
     * Adds a RiskAdjustmentInsuranceClaimType property value.<p>
     *
     *
     * @param newRiskAdjustmentInsuranceClaimType the RiskAdjustmentInsuranceClaimType property value to be added
     */
    void setRiskAdjustmentInsuranceClaimType(RiskAdjustmentInsuranceClaimType newRiskAdjustmentInsuranceClaimType);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000213
     */

    /**
     * Gets all property values for the DiagnosisCodes property.<p>
     *
     * @returns a collection of values for the DiagnosisCodes property.
     * Collection<? extends ClinicalCode> getDiagnosisCodes();
     * ICD codes associated with a RAPS diagnosis cluster
     *
     */
    Collection<ClinicalCode> getDiagnosisCodes();

    /**
     * Add an element to the list
     * ICD codes associated with a RAPS diagnosis cluster
     *
     */
    Collection<ClinicalCode> addDiagnosisCodes(ClinicalCode anItem);

    /**
     * get element from list by Id
     * ICD codes associated with a RAPS diagnosis cluster
     *
     */
    ClinicalCode getDiagnosisCodesById(XUUID anID);

    /**
     * Adds a DiagnosisCodes property value.<p>
     *
     * @param newDiagnosisCodes the DiagnosisCodes property value to be added
     * void setDiagnosisCodes(Collection<? extends ClinicalCode> newDiagnosisCodes);
     * ICD codes associated with a RAPS diagnosis cluster
     *
     */
    void setDiagnosisCodes(Collection<ClinicalCode> newDiagnosisCodes);
    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000214
     */

    /**
     * Gets all property values for the ProviderType property.<p>
     *
     *
     * @returns a collection of values for the ProviderType property.
     */
    ClinicalCode getProviderType();


    /**
     * Adds a ProviderType property value.<p>
     *
     *
     * @param newProviderType the ProviderType property value to be added
     */
    void setProviderType(ClinicalCode newProviderType);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000138
     */

    /**
     * Gets all property values for the AddIndicator property.<p>
     *
     *
     * @returns a collection of values for the AddIndicator property.
     */
    Boolean getAddIndicator();


    /**
     * Adds a AddIndicator property value.<p>
     *
     *
     * @param newAddIndicator the AddIndicator property value to be added
     */
    void setAddIndicator(Boolean newAddIndicator);


    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000215
     */

    /**
     * Gets all property values for the DeleteIndicator property.<p>
     *
     *
     * @returns a collection of values for the DeleteIndicator property.
     */
    Boolean getDeleteIndicator();


    /**
     * Adds a DeleteIndicator property value.<p>
     *
     *
     * @param newDeleteIndicator the DeleteIndicator property value to be added
     */
    void setDeleteIndicator(Boolean newDeleteIndicator);


    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000219
     */

    /**
     * Gets all property values for the MedicareAdvantagePolicyURI property.<p>
     *
     * a pointer to the patient's Medicare advantage policy
     *
     * @returns a collection of values for the MedicareAdvantagePolicyURI property.
     */
    URI getMedicareAdvantagePolicyURI();


    /**
     * Adds a MedicareAdvantagePolicyURI property value.<p>
     *
     * a pointer to the patient's Medicare advantage policy
     *
     * @param newMedicareAdvantagePolicyURI the MedicareAdvantagePolicyURI property value to be added
     */
    void setMedicareAdvantagePolicyURI(URI newMedicareAdvantagePolicyURI);


}
