package com.apixio.model.owl.interfaces;

/**
 OWL annotation driven imports 
**/
import com.apixio.model.owl.interfaces.donotimplement.InformationalEntityIdentifier;
import com.apixio.model.owl.interfaces.donotimplement.TelephoneType;


/**
 * 
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: TelephoneNumber <br>
 * @version generated on Fri Mar 11 09:53:02 PST 2016 by jctoledo
 */

public interface TelephoneNumber  extends InformationalEntityIdentifier {



    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000423
     */

    /**
     * Gets all property values for the TelephoneNumberType property.<p>
     *
     * @returns a collection of values for the TelephoneNumberType property.
     */
    TelephoneType getTelephoneNumberType();


    /**
     * Adds a TelephoneNumberType property value.<p>
     *
     * @param newTelephoneNumberType the TelephoneNumberType property value to be added
     */
    void setTelephoneNumberType(TelephoneType newTelephoneNumberType);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000039
     */

    /**
     * Gets all property values for the PhoneNumber property.<p>
     *
     * @returns a collection of values for the PhoneNumber property.
     */
    String getPhoneNumber();


    /**
     * Adds a PhoneNumber property value.<p>
     *
     * @param newPhoneNumber the PhoneNumber property value to be added
     */
    void setPhoneNumber(String newPhoneNumber);



}
