package com.apixio.model.owl.interfaces;

import com.apixio.model.owl.interfaces.donotimplement.Rendering;

/**
 * OWL annotation driven imports
 **/


/**
 * <p/>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: TextRendering <br>
 *
 * @version generated on Fri Mar 11 09:53:02 PST 2016 by jctoledo
 */

public interface TextRendering extends Rendering {





    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000131
     */

    /**
     * Gets all property values for the TextRenderingType property.<p>
     *
     * @returns a collection of values for the TextRenderingType property.
     */
    String getTextRenderingType();


    /**
     * Adds a TextRenderingType property value.<p>
     *
     * @param newTextRenderingType the TextRenderingType property value to be added
     */
    void setTextRenderingType(String newTextRenderingType);

    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000364
     */

    /**
     * Gets all property values for the TextRenderingValue property.<p>
     *
     * @returns a collection of values for the TextRenderingValue property.
     */
    String getTextRenderingValue();


    /**
     * Adds a TextRenderingValue property value.<p>
     *
     * @param newTextRenderingValue the TextRenderingValue property value to be added
     */
    void setTextRenderingValue(String newTextRenderingValue);


}
