package com.apixio.model.owl.interfaces;

/**
 OWL annotation driven imports 
**/


/**
 * 
 * <p>
 * Generated by Apixio's mod of Protege (http://protege.stanford.edu). <br>
 * Source Class: TimeBoundExternalIdentifier <br>
 * @version generated on Fri Mar 11 09:53:02 PST 2016 by jctoledo
 */

public interface TimeBoundExternalIdentifier  extends com.apixio.model.owl.interfaces.ExternalIdentifier {



    /* ***************************************************
     * Property http://apixio.com/ontology/alo#000016
     */
     
    /**
     * Gets all property values for the TimeBoundIdentifierDateRange property.<p>
     * 
     * @returns a collection of values for the TimeBoundIdentifierDateRange property.
     */
    com.apixio.model.owl.interfaces.DateRange getTimeBoundIdentifierDateRange();


    /**
     * Adds a TimeBoundIdentifierDateRange property value.<p>
     * 
     * @param newTimeBoundIdentifierDateRange the TimeBoundIdentifierDateRange property value to be added
     */
    void setTimeBoundIdentifierDateRange(DateRange newTimeBoundIdentifierDateRange);



}
