package com.apixio.model.patient;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import com.apixio.model.Constants;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown=true)
public class ClinicalCode {
	private String code;
	private String codingSystem;
	private String codingSystemOID;
	private String codingSystemVersion;
	private String displayName;
	
	// eclipse autogenerated stuff
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	public String getCodingSystem() {
		return codingSystem;
	}
	public void setCodingSystem(String codingSystem) {
		this.codingSystem = codingSystem;
	}
	public String getCodingSystemOID() {
		return codingSystemOID;
	}
	public void setCodingSystemOID(String codingSystemOID) {
		this.codingSystemOID = codingSystemOID;
	}
	public String getCodingSystemVersions() {
		return codingSystemVersion;
	}
	public void setCodingSystemVersions(String codingSystemVersions) {
		this.codingSystemVersion = codingSystemVersions;
	}
	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}
	public String getDisplayName() {
		return displayName;
	}

	@Override
	public String toString() {
		return new ToStringBuilder(this, Constants.TO_STRING_STYLE).
	       append("code", code).
	       append("codingSystem", codingSystem).
	       append("codingSystemOID", codingSystemOID).
	       append("codingSystemVersion", codingSystemVersion).
	       append("displayName", displayName).
	       appendSuper(super.toString()).
	       toString();
	}
	@Override
	public boolean equals(Object obj) {
		if(obj!=null && obj instanceof ClinicalCode){
			ClinicalCode codeObj = (ClinicalCode)obj;
			return new EqualsBuilder().append(this.code, codeObj.code)
					.append(this.codingSystem, codeObj.codingSystem)
					.append(this.codingSystemOID, codeObj.codingSystemOID)
					.append(this.codingSystemVersion, codeObj.codingSystemVersion)
					.append(this.displayName, codeObj.displayName).isEquals();
		}
		return false;
	}
	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(this.code)
				.append(this.codingSystem).append(this.codingSystemOID)
				.append(this.codingSystemVersion).append(this.displayName)
				.toHashCode();
	}
	
	
}
