package com.apixio.model.patient;

public enum EncounterType {
	FACE_TO_FACE,
	REAL_TELEPHONY,
	VIRTUAL,
	NON_CLINICAL,
	HOSPTIAL_INPATIENT,
	HOSPTIAL_OUTPATIENT,
	HOSPITAL_INPATIENT,
	HOSPITAL_OUTPATIENT,
	SUPPORT_OP_ENCOUNTER,
	PREADMISSION,
	ADMISSION,
	APPOINTMENT,
	DISCHARGE,
	REQUISITION_ENCOUNTER,
	HOV,
	SURGERY_LOG,
	SURGERY_CASE,
}