daoConfig:

  cqlCacheConfig:
    bufferSize: 100

  globalTableConfig:
    link: apx_cfLink_new
    link2: apx_cfLink
    assembly: apx_cfassembly
    index: apx_cfIndex
    index2: apx_cfIndex
    seq: apx_cfSequenceStore
    metric: apx_cfMetric

fxConfig:
  accessors: com.apixio.accessors.PageWindowsAccessor,com.apixio.accessors.PatientAccessor,com.apixio.accessors.SinglePartialPatientAccessor,com.apixio.accessors.S3PatientAnnotationsAccessor,com.apixio.accessors.SignalGroupsAccessor
  converters: com.apixio.converter.SignalConverter,com.apixio.converter.EventTypeConverter
  jars: accessors/target/apixio-fx-accessors-0.0.2-SNAPSHOT.jar

storageConfig:
  s3Config:
    accessKeyUnencrypted: "AKIARJNA7UNRMBICJPMK"
    secretKeyUnencrypted: "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"
    connectionTimeoutMs: 200000
    socketTimeoutMs: 200000

  apixioFSConfig:
    mountPoint: apixio-documents-test-oregon
    fromStorageType: S3
    toStorageTypes: apixio-documents-test-oregon


patientAnnoConfigV1:
  kafkaTopicBackup.bucket: apixio-backups-kafka-topics
  kafkaTopicBackup.folder: prod/topics/annotationscience_prd/year=%s/month=%s/day=%s
  kafkaTopicBackup.object: prod/topics/annotationscience_prd/year=%s/month=%s/day=%s/annotationscience_prd+%s+%010d.json.gz
  index.bucket: apixio-science-data
  index.prefix: david/fxannotations/patientindex/v1
  localIndexDirectory: /tmp/patientindex/v1
  localLogFile: /tmp/PatientIndex.log.csv

# this is persistence config that's for the purpose of runtime microservice stuff such as ACLs
persistenceConfig:

  # this RDB connection is required to use new (Aug 2019) SignalLogic code
  jdbc_signal_control:
    verboseSql:            true
    connectionUrl:         "jdbc:mysql://mysqlalgocloud-stg101.apixio.com:3306/algocloud"
    driverClassname:       "com.mysql.cj.jdbc.Driver"
    password:              "695LRcuvWkEMUDTW"
    username:              "algocloud"
    maxTotal:              25

  # this RDB connection is required to use "old" SMAS database tables (projectdataset, etc.)
  jdbc_signal_docmeta:
    verboseSql:            true
    connectionUrl:         "jdbc:mysql://localhost:3306/signalmgmt"
    driverClassname:       "com.mysql.cj.jdbc.Driver"
    password:              "root"
    username:              "root"
    maxTotal:              25

  jdbc_apxdatadao:
    verboseSql:            true
    connectionUrl:         "jdbc:mysql://mysqlalgocloud-stg101.apixio.com:3306/algocloud"
    driverClassname:       "com.mysql.cj.jdbc.Driver"
    password:              "695LRcuvWkEMUDTW"
    username:              "algocloud"
    maxTotal:              25

  kafka_patientsvc:
    servers:             "localhost"
    producer:
      keySerializer:     "org.apache.kafka.common.serialization.StringSerializer"
      valueSerializer:   "org.apache.kafka.common.serialization.StringSerializer"

  jedisConfig:
    testWhileIdle: true
    testOnBorrow: true
    maxTotal: 100

  jedisPool:
    timeout: 60000

  # redisConfig is REALLY ONLY FOR microfilters so they can make direct redis calls
  #  for efficiency in checking role/status of users
  redisConfig:
    host: redis-1-stg.apixio.com
    port: 6379
    # prefix for user-account/tokenizer keys (NOT for coordinator keys!):
    keyPrefix: development-

  cassandraConfig_signal:
    hosts: 10.1.16.193,10.1.32.153,10.1.48.121
    binaryPort: 9042
    keyspaceName: signalmgr
    baseDelayMs: 50
    maxDelayMs: 5000
    readConsistencyLevel: LOCAL_QUORUM
    writeConsistencyLevel: LOCAL_QUORUM
    minConnections: 1
    maxConnections: 2
    cqlDebug: false
    batchSyncEnabled: false
    localDC: aws-us-west-2
    username: signalmgrrw-stg
    password: l8cH4PDFqHqdw4Mn
  cassandraConfig_science:
    hosts: 10.1.16.193,10.1.32.153,10.1.48.121
    binaryPort: 9042
    keyspaceName: apixio
    baseDelayMs: 50
    maxDelayMs: 5000
    readConsistencyLevel: LOCAL_QUORUM
    writeConsistencyLevel: LOCAL_QUORUM
    minConnections: 1
    maxConnections: 2
    cqlDebug: false
    batchSyncEnabled: false
    localDC: aws-us-west-2
    username: pipeline-stg
    password: orSEmXXX7s6VS2tk
  cassandraConfig_internal:
    hosts: 10.1.16.77,10.1.48.254,10.1.32.222
    binaryPort: 9042
    keyspaceName: internal
    baseDelayMs: 50
    maxDelayMs: 5000
    readConsistencyLevel: LOCAL_QUORUM
    writeConsistencyLevel: LOCAL_QUORUM
    minConnections: 1
    maxConnections: 2
    cqlDebug: false
    batchSyncEnabled: false
    localDC: aws-us-west-2
    username: pipeline-stg
    password: orSEmXXX7s6VS2tk
  cassandraConfig_application:
    hosts: 10.1.48.137
    binaryPort: 9042
    keyspaceName: application
    baseDelayMs: 50
    maxDelayMs: 5000
    readConsistencyLevel: LOCAL_QUORUM
    writeConsistencyLevel: LOCAL_QUORUM
    minConnections: 1
    maxConnections: 2
    cqlDebug: false
    batchSyncEnabled: false
    localDC: aws-us-west-2
    username: pipeline-stg
    password: orSEmXXX7s6VS2tk

loggingConfig:
  appName: casadmin
  defaultLoggerName: casadmin
  properties:
    graphite: false
    graphiteUrl: http://blah
    graphiteFolderPrefix: cas
    fluent: true
    fluent.url: 127.0.0.1
    fluent.tag: test
