//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.04 at 08:22:48 AM PDT 
//


package com.apixio.model.event.adapters;

import java.util.Date;
import javax.xml.bind.annotation.adapters.XmlAdapter;

public class EventAdapter
    extends XmlAdapter<String, Date>
{


    public Date unmarshal(String value) {
        return (ApixioCustomAdapters.parseDate(value));
    }

    public String marshal(Date value) {
        return (ApixioCustomAdapters.printDate(value));
    }

}
