//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.05 at 03:21:47 PM EDT 
//


package com.apixio.model.xsd.patient;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Actor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Actor">
 *   &lt;complexContent>
 *     &lt;extension base="{}ClinicalBaseObject">
 *       &lt;sequence>
 *         &lt;element name="actorGivenName" type="{}Name"/>
 *         &lt;element name="actorAlternativeName" type="{}Name" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="associatedOrganization" type="{}Organization"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Actor", propOrder = {
    "actorGivenName",
    "actorAlternativeName",
    "title",
    "associatedOrganization"
})
public class Actor
    extends ClinicalBaseObject
{

    @XmlElement(required = true)
    protected Name actorGivenName;
    protected List<Name> actorAlternativeName;
    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected Organization associatedOrganization;

    /**
     * Gets the value of the actorGivenName property.
     * 
     * @return
     *     possible object is
     *     {@link Name }
     *     
     */
    public Name getActorGivenName() {
        return actorGivenName;
    }

    /**
     * Sets the value of the actorGivenName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Name }
     *     
     */
    public void setActorGivenName(Name value) {
        this.actorGivenName = value;
    }

    /**
     * Gets the value of the actorAlternativeName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the actorAlternativeName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActorAlternativeName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Name }
     * 
     * 
     */
    public List<Name> getActorAlternativeName() {
        if (actorAlternativeName == null) {
            actorAlternativeName = new ArrayList<Name>();
        }
        return this.actorAlternativeName;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the associatedOrganization property.
     * 
     * @return
     *     possible object is
     *     {@link Organization }
     *     
     */
    public Organization getAssociatedOrganization() {
        return associatedOrganization;
    }

    /**
     * Sets the value of the associatedOrganization property.
     * 
     * @param value
     *     allowed object is
     *     {@link Organization }
     *     
     */
    public void setAssociatedOrganization(Organization value) {
        this.associatedOrganization = value;
    }

}
