//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.05 at 03:21:47 PM EDT 
//


package com.apixio.model.xsd.patient;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Allergy complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Allergy">
 *   &lt;complexContent>
 *     &lt;extension base="{}CodedBaseObject">
 *       &lt;sequence>
 *         &lt;element name="allergen" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reaction" type="{}Code"/>
 *         &lt;element name="reactionSeverity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="diagnosisDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="reactionDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="resolvedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Allergy", propOrder = {
    "allergen",
    "reaction",
    "reactionSeverity",
    "diagnosisDate",
    "reactionDate",
    "resolvedDate"
})
public class Allergy
    extends CodedBaseObject
{

    @XmlElement(required = true)
    protected String allergen;
    @XmlElement(required = true)
    protected Code reaction;
    @XmlElement(required = true)
    protected String reactionSeverity;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar diagnosisDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar reactionDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar resolvedDate;

    /**
     * Gets the value of the allergen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllergen() {
        return allergen;
    }

    /**
     * Sets the value of the allergen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllergen(String value) {
        this.allergen = value;
    }

    /**
     * Gets the value of the reaction property.
     * 
     * @return
     *     possible object is
     *     {@link Code }
     *     
     */
    public Code getReaction() {
        return reaction;
    }

    /**
     * Sets the value of the reaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Code }
     *     
     */
    public void setReaction(Code value) {
        this.reaction = value;
    }

    /**
     * Gets the value of the reactionSeverity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReactionSeverity() {
        return reactionSeverity;
    }

    /**
     * Sets the value of the reactionSeverity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReactionSeverity(String value) {
        this.reactionSeverity = value;
    }

    /**
     * Gets the value of the diagnosisDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDiagnosisDate() {
        return diagnosisDate;
    }

    /**
     * Sets the value of the diagnosisDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDiagnosisDate(XMLGregorianCalendar value) {
        this.diagnosisDate = value;
    }

    /**
     * Gets the value of the reactionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReactionDate() {
        return reactionDate;
    }

    /**
     * Sets the value of the reactionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReactionDate(XMLGregorianCalendar value) {
        this.reactionDate = value;
    }

    /**
     * Gets the value of the resolvedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getResolvedDate() {
        return resolvedDate;
    }

    /**
     * Sets the value of the resolvedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setResolvedDate(XMLGregorianCalendar value) {
        this.resolvedDate = value;
    }

}
