//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.05 at 03:21:47 PM EDT 
//


package com.apixio.model.xsd.patient;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Anatomy complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Anatomy">
 *   &lt;complexContent>
 *     &lt;extension base="{}CodedBaseObject">
 *       &lt;sequence>
 *         &lt;element name="anatomicalStructureName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Anatomy", propOrder = {
    "anatomicalStructureName"
})
public class Anatomy
    extends CodedBaseObject
{

    @XmlElementRef(name = "anatomicalStructureName", type = JAXBElement.class)
    protected JAXBElement<String> anatomicalStructureName;

    /**
     * Gets the value of the anatomicalStructureName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAnatomicalStructureName() {
        return anatomicalStructureName;
    }

    /**
     * Sets the value of the anatomicalStructureName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAnatomicalStructureName(JAXBElement<String> value) {
        this.anatomicalStructureName = ((JAXBElement<String> ) value);
    }

}
