//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.05 at 03:21:47 PM EDT 
//


package com.apixio.model.xsd.patient;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A CllinicalActor is an actor with a specific (one of the known) clinical role.
 * 
 * <p>Java class for ClinicalActor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClinicalActor">
 *   &lt;complexContent>
 *     &lt;extension base="{}ClinicalBaseObject">
 *       &lt;sequence>
 *         &lt;element name="contactDetails" type="{}ContactDetails"/>
 *         &lt;element name="role">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="ADMINISTERING_PHYSICIAN"/>
 *               &lt;enumeration value="ATTENDING_PHYSICIAN"/>
 *               &lt;enumeration value="CONSULTING_PHYSICIAN"/>
 *               &lt;enumeration value="DIAGNOSING_PHYSICIAN"/>
 *               &lt;enumeration value="INTERPRETING_PHYSICIAN"/>
 *               &lt;enumeration value="ORDERING_PHYSICIAN"/>
 *               &lt;enumeration value="MEDICAL_ASSISTANT"/>
 *               &lt;enumeration value="MEDICAL_HOME_PROVIDER"/>
 *               &lt;enumeration value="NURSE_PRACTITIONER"/>
 *               &lt;enumeration value="PERFORMING_PHYSICIAN"/>
 *               &lt;enumeration value="PRESCRIBING_PHYSICIAN"/>
 *               &lt;enumeration value="PRIMARY_CARE_PROVIDER"/>
 *               &lt;enumeration value="REFERRING_PROVIDER"/>
 *               &lt;enumeration value="REVIEWING_PHYSICIAN"/>
 *               &lt;enumeration value="TECHNICAL_ASSISTANT"/>
 *               &lt;enumeration value="TREATING_PHYSICIAN"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClinicalActor", propOrder = {
    "contactDetails",
    "role"
})
public class ClinicalActor
    extends ClinicalBaseObject
{

    @XmlElement(required = true)
    protected ContactDetails contactDetails;
    @XmlElement(required = true)
    protected String role;

    /**
     * Gets the value of the contactDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ContactDetails }
     *     
     */
    public ContactDetails getContactDetails() {
        return contactDetails;
    }

    /**
     * Sets the value of the contactDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactDetails }
     *     
     */
    public void setContactDetails(ContactDetails value) {
        this.contactDetails = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRole(String value) {
        this.role = value;
    }

}
