//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.05 at 03:21:47 PM EDT 
//


package com.apixio.model.xsd.patient;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * A Coded Base Object is an object which is coded and represents a structured field
 * 
 * <p>Java class for CodedBaseObject complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CodedBaseObject">
 *   &lt;complexContent>
 *     &lt;extension base="{}ClinicalBaseObject">
 *       &lt;sequence>
 *         &lt;element name="primaryClinicalActorId" type="{http://www.w3.org/2001/XMLSchema}ID"/>
 *         &lt;element name="supplementaryClinicalActorId" type="{http://www.w3.org/2001/XMLSchema}ID" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="sourceEncounter" type="{http://www.w3.org/2001/XMLSchema}IDREF"/>
 *         &lt;element name="code" type="{}Code"/>
 *         &lt;element name="codeTranslation" type="{}Code" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CodedBaseObject", propOrder = {
    "primaryClinicalActorId",
    "supplementaryClinicalActorId",
    "sourceEncounter",
    "code",
    "codeTranslation"
})
@XmlSeeAlso({
    Prescription.class,
    Procedure.class,
    BiometricValue.class,
    Anatomy.class,
    Medication.class,
    Administration.class,
    Encounter.class,
    Allergy.class,
    FamilyHistory.class,
    SocialHistory.class,
    Problem.class
})
public class CodedBaseObject
    extends ClinicalBaseObject
{

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String primaryClinicalActorId;
    @XmlElementRef(name = "supplementaryClinicalActorId", type = JAXBElement.class)
    protected List<JAXBElement<String>> supplementaryClinicalActorId;
    @XmlElement(required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object sourceEncounter;
    @XmlElement(required = true)
    protected Code code;
    protected List<Code> codeTranslation;

    /**
     * Gets the value of the primaryClinicalActorId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryClinicalActorId() {
        return primaryClinicalActorId;
    }

    /**
     * Sets the value of the primaryClinicalActorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryClinicalActorId(String value) {
        this.primaryClinicalActorId = value;
    }

    /**
     * Gets the value of the supplementaryClinicalActorId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supplementaryClinicalActorId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupplementaryClinicalActorId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<String>> getSupplementaryClinicalActorId() {
        if (supplementaryClinicalActorId == null) {
            supplementaryClinicalActorId = new ArrayList<JAXBElement<String>>();
        }
        return this.supplementaryClinicalActorId;
    }

    /**
     * Gets the value of the sourceEncounter property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSourceEncounter() {
        return sourceEncounter;
    }

    /**
     * Sets the value of the sourceEncounter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSourceEncounter(Object value) {
        this.sourceEncounter = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link Code }
     *     
     */
    public Code getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link Code }
     *     
     */
    public void setCode(Code value) {
        this.code = value;
    }

    /**
     * Gets the value of the codeTranslation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the codeTranslation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCodeTranslation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Code }
     * 
     * 
     */
    public List<Code> getCodeTranslation() {
        if (codeTranslation == null) {
            codeTranslation = new ArrayList<Code>();
        }
        return this.codeTranslation;
    }

}
