//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.05 at 03:21:47 PM EDT 
//


package com.apixio.model.xsd.patient;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Encounter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Encounter">
 *   &lt;complexContent>
 *     &lt;extension base="{}CodedBaseObject">
 *       &lt;sequence>
 *         &lt;element name="encounterDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="encounterType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="FACE_TO_FACE"/>
 *               &lt;enumeration value="TELEPHONE"/>
 *               &lt;enumeration value="VIRTUAL"/>
 *               &lt;enumeration value="NON_CLINICAL"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="siteOfService" type="{http://www.w3.org/2001/XMLSchema}IDREF"/>
 *         &lt;element name="chiefComplaint" type="{}Code" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Encounter", propOrder = {
    "encounterDate",
    "encounterType",
    "siteOfService",
    "chiefComplaint"
})
public class Encounter
    extends CodedBaseObject
{

    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar encounterDate;
    @XmlElement(required = true)
    protected String encounterType;
    @XmlElement(required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object siteOfService;
    protected List<Code> chiefComplaint;

    /**
     * Gets the value of the encounterDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEncounterDate() {
        return encounterDate;
    }

    /**
     * Sets the value of the encounterDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEncounterDate(XMLGregorianCalendar value) {
        this.encounterDate = value;
    }

    /**
     * Gets the value of the encounterType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncounterType() {
        return encounterType;
    }

    /**
     * Sets the value of the encounterType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncounterType(String value) {
        this.encounterType = value;
    }

    /**
     * Gets the value of the siteOfService property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSiteOfService() {
        return siteOfService;
    }

    /**
     * Sets the value of the siteOfService property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSiteOfService(Object value) {
        this.siteOfService = value;
    }

    /**
     * Gets the value of the chiefComplaint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the chiefComplaint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChiefComplaint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Code }
     * 
     * 
     */
    public List<Code> getChiefComplaint() {
        if (chiefComplaint == null) {
            chiefComplaint = new ArrayList<Code>();
        }
        return this.chiefComplaint;
    }

}
