//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.05 at 03:21:47 PM EDT 
//


package com.apixio.model.xsd.patient;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MaritalStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MaritalStatus">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ANULLED"/>
 *     &lt;enumeration value="DIVORCED"/>
 *     &lt;enumeration value="INTERLOCUTORY"/>
 *     &lt;enumeration value="LEGALLY_SEPARATED"/>
 *     &lt;enumeration value="MARRIED"/>
 *     &lt;enumeration value="POLYGAMOUS"/>
 *     &lt;enumeration value="NEVER_MARRIED"/>
 *     &lt;enumeration value="DOMESTIC_PARTNER"/>
 *     &lt;enumeration value="WIDOWED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MaritalStatus")
@XmlEnum
public enum MaritalStatus {

    ANULLED,
    DIVORCED,
    INTERLOCUTORY,
    LEGALLY_SEPARATED,
    MARRIED,
    POLYGAMOUS,
    NEVER_MARRIED,
    DOMESTIC_PARTNER,
    WIDOWED;

    public String value() {
        return name();
    }

    public static MaritalStatus fromValue(String v) {
        return valueOf(v);
    }

}
