//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.05 at 03:21:47 PM EDT 
//


package com.apixio.model.xsd.patient;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NameType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="NameType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="BIRTH NAME"/>
 *     &lt;enumeration value="NICK NAME"/>
 *     &lt;enumeration value="CURRENT NANE"/>
 *     &lt;enumeration value="MAIDEN NAME"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "NameType")
@XmlEnum
public enum NameType {

    @XmlEnumValue("BIRTH NAME")
    BIRTH_NAME("BIRTH NAME"),
    @XmlEnumValue("NICK NAME")
    NICK_NAME("NICK NAME"),
    @XmlEnumValue("CURRENT NANE")
    CURRENT_NANE("CURRENT NANE"),
    @XmlEnumValue("MAIDEN NAME")
    MAIDEN_NAME("MAIDEN NAME");
    private final String value;

    NameType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static NameType fromValue(String v) {
        for (NameType c: NameType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
