//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.05 at 03:21:47 PM EDT 
//


package com.apixio.model.xsd.patient;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ParsingDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ParsingDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="parsingDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="documentType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="STRUCTURED_DOCUMENT"/>
 *               &lt;enumeration value="NARRATIVE"/>
 *               &lt;enumeration value="ENCOUNTER_NOTE"/>
 *               &lt;enumeration value="IMAGE_OR_SCANNED"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="contentSourceDocumentURI" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="parserType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="CCD"/>
 *               &lt;enumeration value="CCR"/>
 *               &lt;enumeration value="APX"/>
 *               &lt;enumeration value="HL7"/>
 *               &lt;enumeration value="BLUE_BUTTON"/>
 *               &lt;enumeration value="UNSTRUCTURED"/>
 *               &lt;enumeration value="ECW"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="parserVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParsingDetail", propOrder = {
    "parsingDateTime",
    "documentType",
    "contentSourceDocumentURI",
    "parserType",
    "parserVersion"
})
public class ParsingDetail {

    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar parsingDateTime;
    @XmlElement(required = true)
    protected String documentType;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String contentSourceDocumentURI;
    @XmlElement(required = true)
    protected String parserType;
    @XmlElement(required = true)
    protected String parserVersion;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the parsingDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getParsingDateTime() {
        return parsingDateTime;
    }

    /**
     * Sets the value of the parsingDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setParsingDateTime(XMLGregorianCalendar value) {
        this.parsingDateTime = value;
    }

    /**
     * Gets the value of the documentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentType() {
        return documentType;
    }

    /**
     * Sets the value of the documentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentType(String value) {
        this.documentType = value;
    }

    /**
     * Gets the value of the contentSourceDocumentURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentSourceDocumentURI() {
        return contentSourceDocumentURI;
    }

    /**
     * Sets the value of the contentSourceDocumentURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentSourceDocumentURI(String value) {
        this.contentSourceDocumentURI = value;
    }

    /**
     * Gets the value of the parserType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParserType() {
        return parserType;
    }

    /**
     * Sets the value of the parserType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParserType(String value) {
        this.parserType = value;
    }

    /**
     * Gets the value of the parserVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParserVersion() {
        return parserVersion;
    }

    /**
     * Sets the value of the parserVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParserVersion(String value) {
        this.parserVersion = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
