//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.05 at 03:21:47 PM EDT 
//


package com.apixio.model.xsd.patient;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PatientType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PatientType">
 *   &lt;complexContent>
 *     &lt;extension base="{}MetadataMap">
 *       &lt;sequence>
 *         &lt;element name="primaryDemographics" type="{}Demographics"/>
 *         &lt;element name="alternativeDemographics" type="{}Demographics" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="primaryContactDetails" type="{}ContactDetails"/>
 *         &lt;element name="alternateContactDetails" type="{}ContactDetails" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="parsingDetails">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="parsingDetail" type="{}ParsingDetail" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="sources">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="source" type="{}Source" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="careSites">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="careSite" type="{}CareSite" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="clinicalActors">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="clinicalActor" type="{}ClinicalActor" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="problems">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{}MetadataMap">
 *                 &lt;sequence>
 *                   &lt;element name="problem" type="{}Problem" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="procedures">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{}MetadataMap">
 *                 &lt;sequence>
 *                   &lt;element name="procedure" type="{}Procedure" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="prescriptions">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{}MetadataMap">
 *                 &lt;sequence>
 *                   &lt;element name="prescription" type="{}Prescription" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="administrations">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{}MetadataMap">
 *                 &lt;sequence>
 *                   &lt;element name="administration" type="{}Administration" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="externalIds">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{}MetadataMap">
 *                 &lt;sequence>
 *                   &lt;element name="externalId" type="{}ExternalID" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="labResults">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{}MetadataMap">
 *                 &lt;sequence>
 *                   &lt;element name="labResult" type="{}LabResult" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="biometricValues">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="biometricValue" type="{}BiometricValue" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="allergies">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="allergy" type="{}Allergy" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="familyHistories">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="familyHistory" type="{}FamilyHistory" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="socialHistories">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="socialHistory" type="{}SocialHistory" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="encounters">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="encounter" type="{}Encounter" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PatientType", propOrder = {
    "primaryDemographics",
    "alternativeDemographics",
    "primaryContactDetails",
    "alternateContactDetails",
    "parsingDetails",
    "sources",
    "careSites",
    "clinicalActors",
    "problems",
    "procedures",
    "prescriptions",
    "administrations",
    "externalIds",
    "labResults",
    "biometricValues",
    "allergies",
    "familyHistories",
    "socialHistories",
    "encounters"
})
public class PatientType
    extends MetadataMap
{

    @XmlElement(required = true)
    protected Demographics primaryDemographics;
    protected List<Demographics> alternativeDemographics;
    @XmlElement(required = true)
    protected ContactDetails primaryContactDetails;
    protected List<ContactDetails> alternateContactDetails;
    @XmlElement(required = true)
    protected PatientType.ParsingDetails parsingDetails;
    @XmlElement(required = true)
    protected PatientType.Sources sources;
    @XmlElement(required = true)
    protected PatientType.CareSites careSites;
    @XmlElement(required = true)
    protected PatientType.ClinicalActors clinicalActors;
    @XmlElement(required = true)
    protected PatientType.Problems problems;
    @XmlElement(required = true)
    protected PatientType.Procedures procedures;
    @XmlElement(required = true)
    protected PatientType.Prescriptions prescriptions;
    @XmlElement(required = true)
    protected PatientType.Administrations administrations;
    @XmlElement(required = true)
    protected PatientType.ExternalIds externalIds;
    @XmlElement(required = true)
    protected PatientType.LabResults labResults;
    @XmlElement(required = true)
    protected PatientType.BiometricValues biometricValues;
    @XmlElement(required = true)
    protected PatientType.Allergies allergies;
    @XmlElement(required = true)
    protected PatientType.FamilyHistories familyHistories;
    @XmlElement(required = true)
    protected PatientType.SocialHistories socialHistories;
    @XmlElement(required = true)
    protected PatientType.Encounters encounters;

    /**
     * Gets the value of the primaryDemographics property.
     * 
     * @return
     *     possible object is
     *     {@link Demographics }
     *     
     */
    public Demographics getPrimaryDemographics() {
        return primaryDemographics;
    }

    /**
     * Sets the value of the primaryDemographics property.
     * 
     * @param value
     *     allowed object is
     *     {@link Demographics }
     *     
     */
    public void setPrimaryDemographics(Demographics value) {
        this.primaryDemographics = value;
    }

    /**
     * Gets the value of the alternativeDemographics property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alternativeDemographics property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlternativeDemographics().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Demographics }
     * 
     * 
     */
    public List<Demographics> getAlternativeDemographics() {
        if (alternativeDemographics == null) {
            alternativeDemographics = new ArrayList<Demographics>();
        }
        return this.alternativeDemographics;
    }

    /**
     * Gets the value of the primaryContactDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ContactDetails }
     *     
     */
    public ContactDetails getPrimaryContactDetails() {
        return primaryContactDetails;
    }

    /**
     * Sets the value of the primaryContactDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactDetails }
     *     
     */
    public void setPrimaryContactDetails(ContactDetails value) {
        this.primaryContactDetails = value;
    }

    /**
     * Gets the value of the alternateContactDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alternateContactDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlternateContactDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContactDetails }
     * 
     * 
     */
    public List<ContactDetails> getAlternateContactDetails() {
        if (alternateContactDetails == null) {
            alternateContactDetails = new ArrayList<ContactDetails>();
        }
        return this.alternateContactDetails;
    }

    /**
     * Gets the value of the parsingDetails property.
     * 
     * @return
     *     possible object is
     *     {@link PatientType.ParsingDetails }
     *     
     */
    public PatientType.ParsingDetails getParsingDetails() {
        return parsingDetails;
    }

    /**
     * Sets the value of the parsingDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientType.ParsingDetails }
     *     
     */
    public void setParsingDetails(PatientType.ParsingDetails value) {
        this.parsingDetails = value;
    }

    /**
     * Gets the value of the sources property.
     * 
     * @return
     *     possible object is
     *     {@link PatientType.Sources }
     *     
     */
    public PatientType.Sources getSources() {
        return sources;
    }

    /**
     * Sets the value of the sources property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientType.Sources }
     *     
     */
    public void setSources(PatientType.Sources value) {
        this.sources = value;
    }

    /**
     * Gets the value of the careSites property.
     * 
     * @return
     *     possible object is
     *     {@link PatientType.CareSites }
     *     
     */
    public PatientType.CareSites getCareSites() {
        return careSites;
    }

    /**
     * Sets the value of the careSites property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientType.CareSites }
     *     
     */
    public void setCareSites(PatientType.CareSites value) {
        this.careSites = value;
    }

    /**
     * Gets the value of the clinicalActors property.
     * 
     * @return
     *     possible object is
     *     {@link PatientType.ClinicalActors }
     *     
     */
    public PatientType.ClinicalActors getClinicalActors() {
        return clinicalActors;
    }

    /**
     * Sets the value of the clinicalActors property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientType.ClinicalActors }
     *     
     */
    public void setClinicalActors(PatientType.ClinicalActors value) {
        this.clinicalActors = value;
    }

    /**
     * Gets the value of the problems property.
     * 
     * @return
     *     possible object is
     *     {@link PatientType.Problems }
     *     
     */
    public PatientType.Problems getProblems() {
        return problems;
    }

    /**
     * Sets the value of the problems property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientType.Problems }
     *     
     */
    public void setProblems(PatientType.Problems value) {
        this.problems = value;
    }

    /**
     * Gets the value of the procedures property.
     * 
     * @return
     *     possible object is
     *     {@link PatientType.Procedures }
     *     
     */
    public PatientType.Procedures getProcedures() {
        return procedures;
    }

    /**
     * Sets the value of the procedures property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientType.Procedures }
     *     
     */
    public void setProcedures(PatientType.Procedures value) {
        this.procedures = value;
    }

    /**
     * Gets the value of the prescriptions property.
     * 
     * @return
     *     possible object is
     *     {@link PatientType.Prescriptions }
     *     
     */
    public PatientType.Prescriptions getPrescriptions() {
        return prescriptions;
    }

    /**
     * Sets the value of the prescriptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientType.Prescriptions }
     *     
     */
    public void setPrescriptions(PatientType.Prescriptions value) {
        this.prescriptions = value;
    }

    /**
     * Gets the value of the administrations property.
     * 
     * @return
     *     possible object is
     *     {@link PatientType.Administrations }
     *     
     */
    public PatientType.Administrations getAdministrations() {
        return administrations;
    }

    /**
     * Sets the value of the administrations property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientType.Administrations }
     *     
     */
    public void setAdministrations(PatientType.Administrations value) {
        this.administrations = value;
    }

    /**
     * Gets the value of the externalIds property.
     * 
     * @return
     *     possible object is
     *     {@link PatientType.ExternalIds }
     *     
     */
    public PatientType.ExternalIds getExternalIds() {
        return externalIds;
    }

    /**
     * Sets the value of the externalIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientType.ExternalIds }
     *     
     */
    public void setExternalIds(PatientType.ExternalIds value) {
        this.externalIds = value;
    }

    /**
     * Gets the value of the labResults property.
     * 
     * @return
     *     possible object is
     *     {@link PatientType.LabResults }
     *     
     */
    public PatientType.LabResults getLabResults() {
        return labResults;
    }

    /**
     * Sets the value of the labResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientType.LabResults }
     *     
     */
    public void setLabResults(PatientType.LabResults value) {
        this.labResults = value;
    }

    /**
     * Gets the value of the biometricValues property.
     * 
     * @return
     *     possible object is
     *     {@link PatientType.BiometricValues }
     *     
     */
    public PatientType.BiometricValues getBiometricValues() {
        return biometricValues;
    }

    /**
     * Sets the value of the biometricValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientType.BiometricValues }
     *     
     */
    public void setBiometricValues(PatientType.BiometricValues value) {
        this.biometricValues = value;
    }

    /**
     * Gets the value of the allergies property.
     * 
     * @return
     *     possible object is
     *     {@link PatientType.Allergies }
     *     
     */
    public PatientType.Allergies getAllergies() {
        return allergies;
    }

    /**
     * Sets the value of the allergies property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientType.Allergies }
     *     
     */
    public void setAllergies(PatientType.Allergies value) {
        this.allergies = value;
    }

    /**
     * Gets the value of the familyHistories property.
     * 
     * @return
     *     possible object is
     *     {@link PatientType.FamilyHistories }
     *     
     */
    public PatientType.FamilyHistories getFamilyHistories() {
        return familyHistories;
    }

    /**
     * Sets the value of the familyHistories property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientType.FamilyHistories }
     *     
     */
    public void setFamilyHistories(PatientType.FamilyHistories value) {
        this.familyHistories = value;
    }

    /**
     * Gets the value of the socialHistories property.
     * 
     * @return
     *     possible object is
     *     {@link PatientType.SocialHistories }
     *     
     */
    public PatientType.SocialHistories getSocialHistories() {
        return socialHistories;
    }

    /**
     * Sets the value of the socialHistories property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientType.SocialHistories }
     *     
     */
    public void setSocialHistories(PatientType.SocialHistories value) {
        this.socialHistories = value;
    }

    /**
     * Gets the value of the encounters property.
     * 
     * @return
     *     possible object is
     *     {@link PatientType.Encounters }
     *     
     */
    public PatientType.Encounters getEncounters() {
        return encounters;
    }

    /**
     * Sets the value of the encounters property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientType.Encounters }
     *     
     */
    public void setEncounters(PatientType.Encounters value) {
        this.encounters = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{}MetadataMap">
     *       &lt;sequence>
     *         &lt;element name="administration" type="{}Administration" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "administration"
    })
    public static class Administrations
        extends MetadataMap
    {

        protected List<Administration> administration;

        /**
         * Gets the value of the administration property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the administration property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAdministration().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Administration }
         * 
         * 
         */
        public List<Administration> getAdministration() {
            if (administration == null) {
                administration = new ArrayList<Administration>();
            }
            return this.administration;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="allergy" type="{}Allergy" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "allergy"
    })
    public static class Allergies {

        protected List<Allergy> allergy;

        /**
         * Gets the value of the allergy property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the allergy property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAllergy().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Allergy }
         * 
         * 
         */
        public List<Allergy> getAllergy() {
            if (allergy == null) {
                allergy = new ArrayList<Allergy>();
            }
            return this.allergy;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="biometricValue" type="{}BiometricValue" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "biometricValue"
    })
    public static class BiometricValues {

        protected List<BiometricValue> biometricValue;

        /**
         * Gets the value of the biometricValue property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the biometricValue property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBiometricValue().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BiometricValue }
         * 
         * 
         */
        public List<BiometricValue> getBiometricValue() {
            if (biometricValue == null) {
                biometricValue = new ArrayList<BiometricValue>();
            }
            return this.biometricValue;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="careSite" type="{}CareSite" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "careSite"
    })
    public static class CareSites {

        protected List<CareSite> careSite;

        /**
         * Gets the value of the careSite property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the careSite property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCareSite().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CareSite }
         * 
         * 
         */
        public List<CareSite> getCareSite() {
            if (careSite == null) {
                careSite = new ArrayList<CareSite>();
            }
            return this.careSite;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="clinicalActor" type="{}ClinicalActor" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "clinicalActor"
    })
    public static class ClinicalActors {

        protected List<ClinicalActor> clinicalActor;

        /**
         * Gets the value of the clinicalActor property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the clinicalActor property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getClinicalActor().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ClinicalActor }
         * 
         * 
         */
        public List<ClinicalActor> getClinicalActor() {
            if (clinicalActor == null) {
                clinicalActor = new ArrayList<ClinicalActor>();
            }
            return this.clinicalActor;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="encounter" type="{}Encounter" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "encounter"
    })
    public static class Encounters {

        protected List<Encounter> encounter;

        /**
         * Gets the value of the encounter property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the encounter property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEncounter().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Encounter }
         * 
         * 
         */
        public List<Encounter> getEncounter() {
            if (encounter == null) {
                encounter = new ArrayList<Encounter>();
            }
            return this.encounter;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{}MetadataMap">
     *       &lt;sequence>
     *         &lt;element name="externalId" type="{}ExternalID" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "externalId"
    })
    public static class ExternalIds
        extends MetadataMap
    {

        protected List<ExternalID> externalId;

        /**
         * Gets the value of the externalId property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the externalId property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getExternalId().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ExternalID }
         * 
         * 
         */
        public List<ExternalID> getExternalId() {
            if (externalId == null) {
                externalId = new ArrayList<ExternalID>();
            }
            return this.externalId;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="familyHistory" type="{}FamilyHistory" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "familyHistory"
    })
    public static class FamilyHistories {

        protected List<FamilyHistory> familyHistory;

        /**
         * Gets the value of the familyHistory property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the familyHistory property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFamilyHistory().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FamilyHistory }
         * 
         * 
         */
        public List<FamilyHistory> getFamilyHistory() {
            if (familyHistory == null) {
                familyHistory = new ArrayList<FamilyHistory>();
            }
            return this.familyHistory;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{}MetadataMap">
     *       &lt;sequence>
     *         &lt;element name="labResult" type="{}LabResult" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "labResult"
    })
    public static class LabResults
        extends MetadataMap
    {

        protected List<LabResult> labResult;

        /**
         * Gets the value of the labResult property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the labResult property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLabResult().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link LabResult }
         * 
         * 
         */
        public List<LabResult> getLabResult() {
            if (labResult == null) {
                labResult = new ArrayList<LabResult>();
            }
            return this.labResult;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="parsingDetail" type="{}ParsingDetail" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "parsingDetail"
    })
    public static class ParsingDetails {

        protected List<ParsingDetail> parsingDetail;

        /**
         * Gets the value of the parsingDetail property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the parsingDetail property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getParsingDetail().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ParsingDetail }
         * 
         * 
         */
        public List<ParsingDetail> getParsingDetail() {
            if (parsingDetail == null) {
                parsingDetail = new ArrayList<ParsingDetail>();
            }
            return this.parsingDetail;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{}MetadataMap">
     *       &lt;sequence>
     *         &lt;element name="prescription" type="{}Prescription" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "prescription"
    })
    public static class Prescriptions
        extends MetadataMap
    {

        protected List<Prescription> prescription;

        /**
         * Gets the value of the prescription property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the prescription property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPrescription().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Prescription }
         * 
         * 
         */
        public List<Prescription> getPrescription() {
            if (prescription == null) {
                prescription = new ArrayList<Prescription>();
            }
            return this.prescription;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{}MetadataMap">
     *       &lt;sequence>
     *         &lt;element name="problem" type="{}Problem" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "problem"
    })
    public static class Problems
        extends MetadataMap
    {

        protected List<Problem> problem;

        /**
         * Gets the value of the problem property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the problem property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProblem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Problem }
         * 
         * 
         */
        public List<Problem> getProblem() {
            if (problem == null) {
                problem = new ArrayList<Problem>();
            }
            return this.problem;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{}MetadataMap">
     *       &lt;sequence>
     *         &lt;element name="procedure" type="{}Procedure" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "procedure"
    })
    public static class Procedures
        extends MetadataMap
    {

        protected List<Procedure> procedure;

        /**
         * Gets the value of the procedure property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the procedure property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProcedure().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Procedure }
         * 
         * 
         */
        public List<Procedure> getProcedure() {
            if (procedure == null) {
                procedure = new ArrayList<Procedure>();
            }
            return this.procedure;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="socialHistory" type="{}SocialHistory" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "socialHistory"
    })
    public static class SocialHistories {

        protected List<SocialHistory> socialHistory;

        /**
         * Gets the value of the socialHistory property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the socialHistory property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSocialHistory().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SocialHistory }
         * 
         * 
         */
        public List<SocialHistory> getSocialHistory() {
            if (socialHistory == null) {
                socialHistory = new ArrayList<SocialHistory>();
            }
            return this.socialHistory;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="source" type="{}Source" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "source"
    })
    public static class Sources {

        protected List<Source> source;

        /**
         * Gets the value of the source property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the source property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSource().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Source }
         * 
         * 
         */
        public List<Source> getSource() {
            if (source == null) {
                source = new ArrayList<Source>();
            }
            return this.source;
        }

    }

}
