//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.05 at 03:21:47 PM EDT 
//


package com.apixio.model.xsd.patient;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Represents a problem or condition associated with the patient.
 * 
 * <p>Java class for Problem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Problem">
 *   &lt;complexContent>
 *     &lt;extension base="{}CodedBaseObject">
 *       &lt;sequence>
 *         &lt;element name="problemName" type="{http://www.w3.org/2001/XMLSchema}anySimpleType"/>
 *         &lt;element name="resolutionStatus">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="ACTIVE"/>
 *               &lt;enumeration value="INACTIVE"/>
 *               &lt;enumeration value="RESOLVED"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="temporalStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="startDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="diagnosisDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Problem", propOrder = {
    "problemName",
    "resolutionStatus",
    "temporalStatus",
    "startDate",
    "endDate",
    "diagnosisDate"
})
public class Problem
    extends CodedBaseObject
{

    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected Object problemName;
    @XmlElement(required = true)
    protected String resolutionStatus;
    @XmlElement(required = true)
    protected String temporalStatus;
    @XmlElement(required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startDate;
    @XmlElement(required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endDate;
    @XmlElement(required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar diagnosisDate;

    /**
     * Gets the value of the problemName property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getProblemName() {
        return problemName;
    }

    /**
     * Sets the value of the problemName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setProblemName(Object value) {
        this.problemName = value;
    }

    /**
     * Gets the value of the resolutionStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResolutionStatus() {
        return resolutionStatus;
    }

    /**
     * Sets the value of the resolutionStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResolutionStatus(String value) {
        this.resolutionStatus = value;
    }

    /**
     * Gets the value of the temporalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemporalStatus() {
        return temporalStatus;
    }

    /**
     * Sets the value of the temporalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemporalStatus(String value) {
        this.temporalStatus = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the diagnosisDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDiagnosisDate() {
        return diagnosisDate;
    }

    /**
     * Sets the value of the diagnosisDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDiagnosisDate(XMLGregorianCalendar value) {
        this.diagnosisDate = value;
    }

}
