//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.05 at 03:21:47 PM EDT 
//


package com.apixio.model.xsd.patient;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SocialHistory complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SocialHistory">
 *   &lt;complexContent>
 *     &lt;extension base="{}CodedBaseObject">
 *       &lt;sequence>
 *         &lt;element name="socialHistory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SocialHistory", propOrder = {
    "socialHistory"
})
public class SocialHistory
    extends CodedBaseObject
{

    @XmlElement(required = true)
    protected String socialHistory;

    /**
     * Gets the value of the socialHistory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSocialHistory() {
        return socialHistory;
    }

    /**
     * Sets the value of the socialHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSocialHistory(String value) {
        this.socialHistory = value;
    }

}
